// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ProductStatus, ProductType, ProductVisibility, TaxClass } from './enums.js';
import { Money } from '../shared/common.js';

/** @publish */
export interface CreateProductAttributeDto {
  name: string;
  value: string;
  position: number;
}
/** @publish */
export interface CreateProductDto {
  sku: string;
  name: string;
  description: string;
  type: ProductType;
  status: ProductStatus;
  visibility: ProductVisibility;
  price: Money;
  compareAtPrice: Money | null;
  costPrice: Money | null;
  taxClass: TaxClass;
  tags: string[];
}
/** @publish */
export interface DuplicateProductDto {
  sourceId: string;
  newSku: string;
  newName: string;
  copyImages: boolean;
  copyVariants: boolean;
}
/** @publish */
export interface ImportProductDto {
  sku: string;
  name: string;
  price: number;
  currency: string;
  stock: number;
  tags: string;
}
