// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum ProductStatus {
  Draft = 'draft',
  Active = 'active',
  Paused = 'paused',
  Discontinued = 'discontinued',
  Archived = 'archived',
}

/** @publish */
export enum ProductType {
  Physical = 'physical',
  Digital = 'digital',
  Service = 'service',
  Bundle = 'bundle',
  Subscription = 'subscription',
}

/** @publish */
export enum ProductVisibility {
  Public = 'public',
  Private = 'private',
  Hidden = 'hidden',
  PasswordProtected = 'password_protected',
}

/** @publish */
export enum StockPolicy {
  Track = 'track',
  NoTrack = 'no_track',
  DenyOnOutOfStock = 'deny',
  ContinueOnOutOfStock = 'continue',
}

/** @publish */
export enum WeightUnit {
  Gram = 'g',
  Kilogram = 'kg',
  Ounce = 'oz',
  Pound = 'lb',
}

/** @publish */
export enum DimensionUnit {
  Centimeter = 'cm',
  Inch = 'in',
  Meter = 'm',
  Foot = 'ft',
}

/** @publish */
export enum TaxClass {
  Standard = 'standard',
  Reduced = 'reduced',
  Zero = 'zero',
  Exempt = 'exempt',
}
