// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ProductDto, ProductSummaryDto } from './product.dto.js';
import { ProductStatus, ProductType, ProductVisibility } from './enums.js';
import { PageInfo, SortField } from '../shared/pagination.js';
import { Money, DateRange } from '../shared/common.js';

/** @publish */
export interface ProductListResponse {
  items: ProductSummaryDto[];
  pageInfo: PageInfo;
  sort: SortField | null;
}
/** @publish */
export interface ProductDetailResponse {
  product: ProductDto;
  relatedProductIds: string[];
  variantCount: number;
}
/** @publish */
export interface ProductSearchDto {
  query: string | null;
  type: ProductType | null;
  status: ProductStatus | null;
  visibility: ProductVisibility | null;
  minPrice: number | null;
  maxPrice: number | null;
  tags: string[];
  inStock: boolean | null;
  dateRange: DateRange | null;
}
/** @publish */
export interface ProductStatsDto {
  total: number;
  active: number;
  draft: number;
  outOfStock: number;
  byType: Record<string,number>;
  totalInventoryValue: Money;
  averagePrice: Money;
}
/** @publish */
export interface ProductExportDto {
  format: 'csv' | 'xlsx' | 'json';
  includeVariants: boolean;
  includeImages: boolean;
  filter: ProductSearchDto;
}
