// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ProductStatus, ProductType, ProductVisibility, TaxClass } from './enums.js';
import { UUID, ISODateString, Money } from '../shared/common.js';
import { ImageDto } from '../shared/media.js';

/** @publish */
export interface ProductDimensionsDto {
  length: number;
  width: number;
  height: number;
  unit: string;
}
/** @publish */
export interface ProductWeightDto {
  value: number;
  unit: string;
}
/** @publish */
export interface ProductSeoDto {
  title: string | null;
  description: string | null;
  slug: string;
  canonicalUrl: string | null;
  keywords: string[];
}
/** @publish */
export interface ProductAttributeDto {
  id: UUID;
  name: string;
  value: string;
  position: number;
  isVisible: boolean;
  isFilterable: boolean;
}
/** @publish */
export interface ProductDto {
  id: UUID;
  sku: string;
  barcode: string | null;
  name: string;
  description: string;
  type: ProductType;
  status: ProductStatus;
  visibility: ProductVisibility;
  price: Money;
  compareAtPrice: Money | null;
  costPrice: Money | null;
  taxClass: TaxClass;
  images: ImageDto[];
  tags: string[];
  dimensions: ProductDimensionsDto | null;
  weight: ProductWeightDto | null;
  seo: ProductSeoDto;
  attributes: ProductAttributeDto[];
  createdAt: ISODateString;
  updatedAt: ISODateString;
}
/** @publish */
export interface ProductSummaryDto {
  id: UUID;
  sku: string;
  name: string;
  status: ProductStatus;
  price: Money;
  thumbnail: ImageDto | null;
}
