// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ProductStatus, ProductVisibility, TaxClass } from './enums.js';
import { Money } from '../shared/common.js';

/** @publish */
export interface UpdateProductDto {
  name: string | null;
  description: string | null;
  status: ProductStatus | null;
  visibility: ProductVisibility | null;
  price: Money | null;
  compareAtPrice: Money | null;
  taxClass: TaxClass | null;
  tags: string[] | null;
}
/** @publish */
export interface UpdateProductSeoDto {
  title: string | null;
  description: string | null;
  slug: string | null;
  keywords: string[] | null;
}
/** @publish */
export interface UpdateProductDimensionsDto {
  length: number | null;
  width: number | null;
  height: number | null;
  unit: string | null;
}
/** @publish */
export interface BulkUpdateProductsDto {
  productIds: string[];
  status: ProductStatus | null;
  tags: string[] | null;
}
