// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { StockPolicy } from './enums.js';
import { UUID, ISODateString, Money } from '../shared/common.js';
import { ProductAttributeDto } from './product.dto.js';

/** @publish */
export interface VariantOptionDto {
  name: string;
  values: string[];
}
/** @publish */
export interface ProductVariantDto {
  id: UUID;
  productId: UUID;
  sku: string;
  barcode: string | null;
  price: Money;
  compareAtPrice: Money | null;
  costPrice: Money | null;
  stockPolicy: StockPolicy;
  stock: number;
  reservedStock: number;
  attributes: ProductAttributeDto[];
  isDefault: boolean;
  isAvailable: boolean;
  createdAt: ISODateString;
}
/** @publish */
export interface CreateVariantDto {
  sku: string;
  price: Money;
  compareAtPrice: Money | null;
  stock: number;
  attributes: Array<{name:string;value:string}>;
  isDefault: boolean;
}
/** @publish */
export interface UpdateVariantDto {
  price: Money | null;
  compareAtPrice: Money | null;
  stock: number | null;
  isDefault: boolean | null;
}
/** @publish */
export interface BulkUpdateVariantsDto {
  variantIds: UUID[];
  price: Money | null;
  stock: number | null;
}
