// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { CouponStatus } from './enums.js';
import { UUID, ISODateString, Money } from '../shared/common.js';

/** @publish */
export interface CouponDto {
  id: UUID;
  code: string;
  discountId: UUID;
  status: CouponStatus;
  usageLimit: number | null;
  usageCount: number;
  perCustomerLimit: number | null;
  isPublic: boolean;
  expiresAt: ISODateString | null;
  createdAt: ISODateString;
}
/** @publish */
export interface CreateCouponDto {
  discountId: UUID;
  code: string | null;
  usageLimit: number | null;
  perCustomerLimit: number | null;
  expiresAt: ISODateString | null;
  isPublic: boolean;
}
/** @publish */
export interface BulkCreateCouponsDto {
  discountId: UUID;
  count: number;
  prefix: string | null;
  usageLimit: number | null;
  expiresAt: ISODateString | null;
}
/** @publish */
export interface ValidateCouponDto {
  code: string;
  userId: string | null;
  orderValue: Money;
  productIds: UUID[];
}
/** @publish */
export interface CouponValidationResultDto {
  valid: boolean;
  coupon: CouponDto | null;
  discountAmount: Money | null;
  reason: string | null;
}
