// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { DiscountType, DiscountTarget } from './enums.js';
import { Money, ISODateString } from '../shared/common.js';

/** @publish */
export interface CreateDiscountConditionDto {
  minOrderValue: Money | null;
  minQuantity: number | null;
  requiredProductIds: string[];
  requiredCategoryIds: string[];
  allowedUserRoles: string[];
}
/** @publish */
export interface CreateDiscountDto {
  name: string;
  description: string | null;
  type: DiscountType;
  target: DiscountTarget;
  value: number;
  maxDiscountAmount: Money | null;
  conditions: CreateDiscountConditionDto;
  usageLimit: number | null;
  perCustomerLimit: number | null;
  startsAt: ISODateString;
  endsAt: ISODateString | null;
}
/** @publish */
export interface UpdateDiscountDto {
  name: string | null;
  description: string | null;
  value: number | null;
  usageLimit: number | null;
  endsAt: ISODateString | null;
}
