// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { DiscountDto, DiscountSummaryDto } from './discount.dto.js';
import { CouponDto } from './coupon.dto.js';
import { DiscountStatus, DiscountType } from './enums.js';
import { PageInfo } from '../shared/pagination.js';
import { Money, DateRange } from '../shared/common.js';

/** @publish */
export interface DiscountListResponse {
  items: DiscountSummaryDto[];
  pageInfo: PageInfo;
}
/** @publish */
export interface DiscountDetailResponse {
  discount: DiscountDto;
  coupons: CouponDto[];
  recentUsage: number;
}
/** @publish */
export interface DiscountFilterDto {
  status: DiscountStatus | null;
  type: DiscountType | null;
  search: string | null;
  activeNow: boolean;
  dateRange: DateRange | null;
}
/** @publish */
export interface DiscountStatsDto {
  totalSaved: Money;
  usageCount: number;
  activeDiscounts: number;
  topDiscounts: DiscountSummaryDto[];
}
