// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { DiscountType, DiscountStatus, DiscountTarget } from './enums.js';
import { UUID, ISODateString, Money } from '../shared/common.js';

/** @publish */
export interface DiscountConditionDto {
  minOrderValue: Money | null;
  minQuantity: number | null;
  requiredProductIds: UUID[];
  requiredCategoryIds: UUID[];
  allowedUserRoles: string[];
}
/** @publish */
export interface DiscountDto {
  id: UUID;
  name: string;
  description: string | null;
  type: DiscountType;
  status: DiscountStatus;
  target: DiscountTarget;
  value: number;
  maxDiscountAmount: Money | null;
  conditions: DiscountConditionDto;
  usageLimit: number | null;
  usageCount: number;
  perCustomerLimit: number | null;
  startsAt: ISODateString;
  endsAt: ISODateString | null;
  createdAt: ISODateString;
}
/** @publish */
export interface DiscountSummaryDto {
  id: UUID;
  name: string;
  type: DiscountType;
  status: DiscountStatus;
  value: number;
  usageCount: number;
  endsAt: ISODateString | null;
}
