// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum DiscountType {
  Percentage = 'percentage',
  FixedAmount = 'fixed_amount',
  FreeShipping = 'free_shipping',
  BuyXGetY = 'buy_x_get_y',
  Bundle = 'bundle',
}

/** @publish */
export enum DiscountStatus {
  Draft = 'draft',
  Active = 'active',
  Paused = 'paused',
  Expired = 'expired',
  Exhausted = 'exhausted',
}

/** @publish */
export enum DiscountTarget {
  AllProducts = 'all_products',
  SpecificProducts = 'specific_products',
  SpecificCategories = 'specific_categories',
  SpecificCollections = 'specific_collections',
}

/** @publish */
export enum CouponStatus {
  Active = 'active',
  Inactive = 'inactive',
  Expired = 'expired',
  Exhausted = 'exhausted',
}
