// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export type UUID = string;

/** @publish */
export type ISODateString = string;

/** @publish */
export type Currency =
  | "USD"
  | "EUR"
  | "GBP"
  | "JPY"
  | "CAD"
  | "AUD"
  | "CHF"
  | "SEK"
  | "NOK"
  | "DKK";

/** @publish */
export type Locale = string;

/** @publish */
export type Timezone = string;

/** @publish */
export interface Money {
  amount: number;
  currency: Currency;
  formatted: string;
}

/** @publish */
export interface Address {
  line1: string;
  line2: string | null;
  city: string;
  state: string;
  postalCode: string;
  countryCode: string;
  isDefault: boolean;
}

/** @publish */
export interface PhoneNumber {
  countryCode: string;
  number: string;
  extension: string | null;
}

/** @publish */
export interface DateRange {
  from: ISODateString;
  to: ISODateString;
}

/** @publish */
export interface TimeRange {
  fromHour: number;
  fromMinute: number;
  toHour: number;
  toMinute: number;
}

/** @publish */
export interface GeoCoordinates {
  latitude: number;
  longitude: number;
  altitude: number | null;
}

/** @publish */
export interface ApiError {
  code: string;
  message: string;
  field: string | null;
  details: string[];
}

/** @publish */
export interface ApiResponse<T> {
  data: T;
  success: boolean;
  errors: ApiError[];
  requestId: string;
  timestamp: ISODateString;
}

/** @publish */
export interface BulkOperationResult {
  succeeded: number;
  failed: number;
  errors: ApiError[];
}

/** @publish */
export interface AuditEntry {
  actorId: UUID;
  action: string;
  resourceType: string;
  resourceId: UUID;
  timestamp: ISODateString;
  ipAddress: string;
}

/** @publish */
export interface Webhook {
  id: UUID;
  url: string;
  secret: string;
  events: string[];
  active: boolean;
  createdAt: ISODateString;
}
