// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export type TranslationKey = string;

/** @publish */
export type TranslationMap = Record<TranslationKey, string>;

/** @publish */
export interface LocalizedString {
  defaultValue: string;
  translations: Record<Locale, string>;
}

/** @publish */
export interface TranslationDto {
  key: TranslationKey;
  locale: Locale;
  value: string;
  updatedAt: ISODateString;
}

/** @publish */
export interface LocaleConfig {
  code: Locale;
  name: string;
  nativeName: string;
  rtl: boolean;
  enabled: boolean;
}
