// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ISODateString, UUID } from "./common.js";

/** @publish */
export enum MediaType {
  Image = "image",
  Video = "video",
  Document = "document",
  Audio = "audio",
  Archive = "archive",
}

/** @publish */
export enum ImageFormat {
  JPEG = "jpeg",
  PNG = "png",
  WebP = "webp",
  GIF = "gif",
  SVG = "svg",
  AVIF = "avif",
}

/** @publish */
export interface ImageVariant {
  width: number;
  height: number;
  url: string;
  format: ImageFormat;
  sizeBytes: number;
}

/** @publish */
export interface ImageDto {
  id: UUID;
  url: string;
  altText: string | null;
  width: number;
  height: number;
  format: ImageFormat;
  variants: ImageVariant[];
  createdAt: ISODateString;
}

/** @publish */
export interface VideoDto {
  id: UUID;
  url: string;
  thumbnailUrl: string;
  durationSeconds: number;
  width: number;
  height: number;
  sizeBytes: number;
  mimeType: string;
}

/** @publish */
export interface DocumentDto {
  id: UUID;
  url: string;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  pageCount: number | null;
}

/** @publish */
export interface MediaUploadUrlDto {
  uploadUrl: string;
  fields: Record<string, string>;
  expiresAt: ISODateString;
  maxSizeBytes: number;
}

/** @publish */
export interface MediaDto {
  id: UUID;
  type: MediaType;
  url: string;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  createdAt: ISODateString;
}
