// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export type SortOrder = "asc" | "desc";

/** @publish */
export type CursorToken = string;

/** @publish */
export interface PageInfo {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
}

/** @publish */
export interface CursorPageInfo {
  cursor: CursorToken | null;
  hasNext: boolean;
  count: number;
}

/** @publish */
export interface SortField {
  field: string;
  order: SortOrder;
}

/** @publish */
export interface PaginationInput {
  page: number;
  pageSize: number;
  sort: SortField[];
}

/** @publish */
export interface PaginatedResponse<T> {
  items: T[];
  pageInfo: PageInfo;
  sort: SortField | null;
}

/** @publish */
export interface CursorResponse<T> {
  edges: T[];
  pageInfo: CursorPageInfo;
}
