// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { OrderChannel } from './enums.js';
import { Address } from '../shared/common.js';

/** @publish */
export interface OrderLineInputDto {
  productId: string;
  variantId: string | null;
  quantity: number;
  customPrice: number | null;
}
/** @publish */
export interface CreateOrderDto {
  userId: string | null;
  guestEmail: string | null;
  channel: OrderChannel;
  lines: OrderLineInputDto[];
  shippingAddress: Address;
  billingAddress: Address | null;
  couponCodes: string[];
  notes: string | null;
  tags: string[];
}
/** @publish */
export interface CreateDraftOrderDto {
  userId: string | null;
  lines: OrderLineInputDto[];
  notes: string | null;
}
/** @publish */
export interface AddOrderLineDto {
  productId: string;
  variantId: string | null;
  quantity: number;
}
/** @publish */
export interface UpdateOrderLineDto {
  lineId: string;
  quantity: number;
}
