// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum OrderStatus {
  Draft = 'draft',
  PendingPayment = 'pending_payment',
  PaymentFailed = 'payment_failed',
  Confirmed = 'confirmed',
  Processing = 'processing',
  PartiallyFulfilled = 'partially_fulfilled',
  Fulfilled = 'fulfilled',
  Shipped = 'shipped',
  OutForDelivery = 'out_for_delivery',
  Delivered = 'delivered',
  Cancelled = 'cancelled',
  Refunded = 'refunded',
  PartiallyRefunded = 'partially_refunded',
  Disputed = 'disputed',
}

/** @publish */
export enum FulfillmentStatus {
  Unfulfilled = 'unfulfilled',
  PartiallyFulfilled = 'partially_fulfilled',
  Fulfilled = 'fulfilled',
  Restocked = 'restocked',
}

/** @publish */
export enum ReturnReason {
  WrongItem = 'wrong_item',
  Defective = 'defective',
  NotAsDescribed = 'not_as_described',
  ChangeOfMind = 'change_of_mind',
  Duplicate = 'duplicate',
  Other = 'other',
}

/** @publish */
export enum ReturnStatus {
  Requested = 'requested',
  Approved = 'approved',
  Rejected = 'rejected',
  Received = 'received',
  Completed = 'completed',
}

/** @publish */
export enum OrderChannel {
  Web = 'web',
  Mobile = 'mobile',
  Api = 'api',
  POS = 'pos',
  Phone = 'phone',
}
