// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { FulfillmentStatus, ReturnReason, ReturnStatus } from './enums.js';
import { UUID, ISODateString, Money, Address } from '../shared/common.js';

/** @publish */
export interface FulfillmentLineDto {
  lineId: UUID;
  quantity: number;
}
/** @publish */
export interface FulfillmentDto {
  id: UUID;
  orderId: UUID;
  status: FulfillmentStatus;
  trackingNumber: string | null;
  trackingUrl: string | null;
  carrier: string | null;
  lines: FulfillmentLineDto[];
  shippedAt: ISODateString | null;
  createdAt: ISODateString;
}
/** @publish */
export interface CreateFulfillmentDto {
  lines: FulfillmentLineDto[];
  trackingNumber: string | null;
  carrier: string | null;
  notifyCustomer: boolean;
}
/** @publish */
export interface OrderReturnLineDto {
  lineId: UUID;
  quantity: number;
  reason: ReturnReason;
}
/** @publish */
export interface OrderReturnDto {
  id: UUID;
  orderId: UUID;
  status: ReturnStatus;
  lines: OrderReturnLineDto[];
  refundAmount: Money;
  notes: string | null;
  createdAt: ISODateString;
}
/** @publish */
export interface CreateReturnDto {
  lines: OrderReturnLineDto[];
  notes: string | null;
  refundToOriginalPayment: boolean;
}
