// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { OrderStatus, FulfillmentStatus, OrderChannel } from './enums.js';
import { UUID, ISODateString, Money, Address } from '../shared/common.js';

/** @publish */
export interface TaxLineDto {
  title: string;
  rate: number;
  price: Money;
}
/** @publish */
export interface DiscountAllocationDto {
  amount: Money;
  discountId: UUID;
  description: string;
}
/** @publish */
export interface OrderLineDto {
  id: UUID;
  productId: UUID;
  variantId: UUID | null;
  sku: string;
  name: string;
  quantity: number;
  unitPrice: Money;
  totalPrice: Money;
  discount: Money | null;
  tax: Money;
  fulfillmentStatus: FulfillmentStatus;
}
/** @publish */
export interface OrderDto {
  id: UUID;
  displayId: string;
  userId: UUID;
  guestEmail: string | null;
  status: OrderStatus;
  channel: OrderChannel;
  lines: OrderLineDto[];
  shippingAddress: Address;
  billingAddress: Address;
  subtotal: Money;
  discount: Money;
  tax: Money;
  shippingCost: Money;
  total: Money;
  taxLines: TaxLineDto[];
  notes: string | null;
  tags: string[];
  createdAt: ISODateString;
  updatedAt: ISODateString;
}
/** @publish */
export interface OrderTimelineEventDto {
  id: UUID;
  type: string;
  message: string;
  actorId: UUID | null;
  metadata: Record<string,string>;
  occurredAt: ISODateString;
}
