// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { OrderDto, OrderTimelineEventDto } from './order.dto.js';
import { OrderStatus, FulfillmentStatus, OrderChannel } from './enums.js';
import { PageInfo, SortField } from '../shared/pagination.js';
import { Money, DateRange } from '../shared/common.js';

/** @publish */
export interface OrderListResponse {
  items: OrderDto[];
  pageInfo: PageInfo;
  sort: SortField | null;
}
/** @publish */
export interface OrderDetailResponse {
  order: OrderDto;
  timeline: OrderTimelineEventDto[];
}
/** @publish */
export interface OrderFilterDto {
  userId: string | null;
  guestEmail: string | null;
  status: OrderStatus | null;
  fulfillmentStatus: FulfillmentStatus | null;
  channel: OrderChannel | null;
  dateRange: DateRange | null;
  search: string | null;
  minTotal: number | null;
  maxTotal: number | null;
  tags: string[];
}
/** @publish */
export interface OrderStatsDto {
  total: number;
  totalRevenue: Money;
  averageOrderValue: Money;
  byStatus: Record<string,number>;
  byChannel: Record<string,number>;
  cancelRate: number;
  returnRate: number;
}
/** @publish */
export interface ReorderDto {
  orderId: string;
  adjustQuantities: boolean;
}
