// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum CartStatus {
  Active = 'active',
  Abandoned = 'abandoned',
  Converted = 'converted',
  Expired = 'expired',
}

/** @publish */
export interface CartLineItemDto {
  id: UUID;
  variantId: UUID;
  productId: UUID;
  name: string;
  sku: string;
  quantity: number;
  unitPrice: Money;
  compareAtPrice: Money | null;
  total: Money;
  imageUrl: string | null;
  inStock: boolean;
  maxQuantity: number | null;
}

/** @publish */
export interface CartDto {
  id: UUID;
  status: CartStatus;
  customerId: UUID | null;
  sessionId: string;
  lineItems: CartLineItemDto[];
  discountCodes: string[];
  shippingAddress: Address | null;
  subtotal: Money;
  estimatedShipping: Money | null;
  estimatedTax: Money | null;
  discountTotal: Money;
  total: Money;
  currency: Currency;
  updatedAt: ISODateString;
  expiresAt: ISODateString;
}

/** @publish */
export interface AddToCartDto {
  variantId: UUID;
  quantity: number;
  customAttributes: JSONObject | null;
}

/** @publish */
export interface UpdateCartLineItemDto {
  quantity: number;
}

/** @publish */
export interface ApplyCartDiscountDto {
  code: string;
}

/** @publish */
export interface CartCheckoutDto {
  cartId: UUID;
  email: EmailAddress;
  billingAddress: Address;
  shippingAddress: Address;
  shippingRateId: string | null;
  paymentMethodId: string | null;
}
