// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum DraftOrderStatus {
  Open = 'open',
  Invoice_sent = 'invoice_sent',
  Completed = 'completed',
  Cancelled = 'cancelled',
}

/** @publish */
export interface DraftOrderLineItemDto {
  variantId: UUID | null;
  title: string;
  sku: string | null;
  quantity: number;
  unitPrice: Money;
  requiresShipping: boolean;
  taxable: boolean;
}

/** @publish */
export interface DraftOrderDto {
  id: UUID;
  status: DraftOrderStatus;
  customerId: UUID | null;
  email: EmailAddress | null;
  billingAddress: Address | null;
  shippingAddress: Address | null;
  lineItems: DraftOrderLineItemDto[];
  shippingLine: OrderShippingLineDto | null;
  discountCodes: string[];
  note: string | null;
  invoiceSentAt: ISODateString | null;
  completedOrderId: UUID | null;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

/** @publish */
export interface CreateDraftOrderDto {
  customerId: UUID | null;
  email: EmailAddress | null;
  billingAddress: Address | null;
  shippingAddress: Address | null;
  lineItems: DraftOrderLineItemDto[];
  discountCodes: string[];
  note: string | null;
}

/** @publish */
export interface UpdateDraftOrderDto {
  customerId: UUID | null;
  email: EmailAddress | null;
  lineItems: DraftOrderLineItemDto[] | null;
  note: string | null;
}

/** @publish */
export interface SendDraftOrderInvoiceDto {
  to: EmailAddress;
  subject: string | null;
  message: string | null;
}

/** @publish */
export interface CompleteDraftOrderDto {
  paymentPending: boolean;
}
