// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum FulfillmentEventType {
  FulfillmentCreated = 'fulfillment_created',
  Picked = 'picked',
  Packed = 'packed',
  ReadyForPickup = 'ready_for_pickup',
  LabelCreated = 'label_created',
  Shipped = 'shipped',
  InTransit = 'in_transit',
  OutForDelivery = 'out_for_delivery',
  AttemptFailed = 'attempt_failed',
  Delivered = 'delivered',
  Exception = 'exception',
  Returned = 'returned',
}

/** @publish */
export interface TrackingDto {
  number: string;
  url: string | null;
  carrier: string;
  estimatedDelivery: ISODateString | null;
}

/** @publish */
export interface FulfillmentDto {
  id: UUID;
  orderId: UUID;
  status: FulfillmentStatus;
  lineItems: Array<{ lineItemId: UUID; quantity: number }>;
  trackingInfo: TrackingDto[];
  shippingLabel: string | null;
  service: string | null;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

/** @publish */
export interface FulfillmentEventDto {
  id: UUID;
  fulfillmentId: UUID;
  type: FulfillmentEventType;
  message: string | null;
  location: string | null;
  timestamp: ISODateString;
}

/** @publish */
export interface CreateFulfillmentDto {
  lineItems: Array<{ lineItemId: UUID; quantity: number }>;
  trackingNumber: string | null;
  trackingUrl: string | null;
  carrier: string | null;
  notifyCustomer: boolean;
  service: string | null;
}

/** @publish */
export interface UpdateFulfillmentDto {
  trackingNumber: string | null;
  trackingUrl: string | null;
  carrier: string | null;
  notifyCustomer: boolean;
}

/** @publish */
export interface CancelFulfillmentDto {
  reason: string;
  notifyCustomer: boolean;
  restockItems: boolean;
}

/** @publish */
export interface BulkFulfillDto {
  orderIds: UUID[];
  notifyCustomer: boolean;
  trackingNumber: string | null;
}
