// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export interface CreateOrderDto {
  customerId: UUID | null;
  email: EmailAddress;
  phone: PhoneNumberString | null;
  billingAddress: Address;
  shippingAddress: Address;
  lineItems: Array<{ variantId: UUID; quantity: number; unitPrice: Money }>;
  shippingLineId: UUID | null;
  discountCodes: string[];
  note: string | null;
  tags: Tag[];
  source: OrderSource;
}

/** @publish */
export interface UpdateOrderDto {
  note: string | null;
  tags: Tag[] | null;
  billingAddress: Address | null;
  shippingAddress: Address | null;
}

/** @publish */
export interface OrderFilterDto {
  status: OrderStatus | null;
  paymentStatus: PaymentStatus | null;
  fulfillmentStatus: FulfillmentStatus | null;
  customerId: UUID | null;
  source: OrderSource | null;
  search: string | null;
  createdAfter: ISODateString | null;
  createdBefore: ISODateString | null;
  minTotal: number | null;
  maxTotal: number | null;
  currency: Currency | null;
  tags: Tag[] | null;
}

/** @publish */
export interface OrderListResponseDto {
  orders: OrderDto[];
  pageInfo: PageInfo;
  totalCount: number;
  totalRevenue: Money;
}

/** @publish */
export interface CancelOrderDto {
  reason: string;
  notify: boolean;
  restock: boolean;
}

/** @publish */
export interface AddOrderNoteDto {
  note: string;
  internal: boolean;
}

/** @publish */
export interface OrderNoteDto {
  id: UUID;
  orderId: UUID;
  note: string;
  internal: boolean;
  authorId: UUID;
  createdAt: ISODateString;
}

/** @publish */
export interface TagOrderDto {
  tags: Tag[];
}

/** @publish */
export interface DuplicateOrderDto {
  orderId: UUID;
}
