// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum OrderStatus {
  Draft = 'draft',
  Pending = 'pending',
  Confirmed = 'confirmed',
  Processing = 'processing',
  Packed = 'packed',
  Shipped = 'shipped',
  OutForDelivery = 'out_for_delivery',
  Delivered = 'delivered',
  PartiallyDelivered = 'partially_delivered',
  ReturnRequested = 'return_requested',
  Returned = 'returned',
  Cancelled = 'cancelled',
  Refunded = 'refunded',
}

/** @publish */
export enum FulfillmentStatus {
  Unfulfilled = 'unfulfilled',
  PartiallyFulfilled = 'partially_fulfilled',
  Fulfilled = 'fulfilled',
  Restocked = 'restocked',
}

/** @publish */
export enum PaymentStatus {
  Pending = 'pending',
  Authorized = 'authorized',
  PartiallyPaid = 'partially_paid',
  Paid = 'paid',
  PartiallyRefunded = 'partially_refunded',
  Refunded = 'refunded',
  Voided = 'voided',
  Failed = 'failed',
}

/** @publish */
export enum OrderSource {
  Web = 'web',
  MobileApp = 'mobile_app',
  POS = 'pos',
  API = 'api',
  Import = 'import',
  Phone = 'phone',
  EDI = 'edi',
}

/** @publish */
export interface OrderLineItemDto {
  id: UUID;
  productId: UUID;
  variantId: UUID;
  sku: string;
  name: string;
  quantity: number;
  unitPrice: Money;
  discount: Money;
  tax: Money;
  subtotal: Money;
  total: Money;
  weight: ProductWeight | null;
  requiresShipping: boolean;
  fulfillmentStatus: FulfillmentStatus;
  returnableQuantity: number;
}

/** @publish */
export interface OrderTaxLineDto {
  title: string;
  rate: number;
  price: Money;
}

/** @publish */
export interface OrderDiscountAllocationDto {
  discountId: UUID;
  title: string;
  type: string;
  amount: Money;
}

/** @publish */
export interface OrderShippingLineDto {
  id: UUID;
  title: string;
  carrierName: string | null;
  price: Money;
  discountedPrice: Money;
  taxLines: OrderTaxLineDto[];
}

/** @publish */
export interface OrderDto {
  id: UUID;
  orderNumber: string;
  status: OrderStatus;
  paymentStatus: PaymentStatus;
  fulfillmentStatus: FulfillmentStatus;
  source: OrderSource;
  customerId: UUID | null;
  email: EmailAddress;
  phone: PhoneNumberString | null;
  billingAddress: Address;
  shippingAddress: Address;
  lineItems: OrderLineItemDto[];
  shippingLines: OrderShippingLineDto[];
  taxLines: OrderTaxLineDto[];
  discountAllocations: OrderDiscountAllocationDto[];
  subtotal: Money;
  shippingTotal: Money;
  taxTotal: Money;
  discountTotal: Money;
  total: Money;
  refundedTotal: Money;
  note: string | null;
  tags: Tag[];
  currency: Currency;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}
