// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum RefundReason {
  CustomerRequest = 'customer_request',
  Defective = 'defective',
  WrongItem = 'wrong_item',
  NotAsDescribed = 'not_as_described',
  ArrivalDamage = 'arrival_damage',
  NeverReceived = 'never_received',
  Other = 'other',
}

/** @publish */
export enum RefundStatus {
  Pending = 'pending',
  Processing = 'processing',
  Completed = 'completed',
  Failed = 'failed',
  Cancelled = 'cancelled',
}

/** @publish */
export enum RestockType {
  Return = 'return',
  Cancel = 'cancel',
  LegacyRestock = 'legacy_restock',
  NoRestock = 'no_restock',
}

/** @publish */
export interface RefundLineItemDto {
  lineItemId: UUID;
  quantity: number;
  amount: Money;
  restockType: RestockType;
}

/** @publish */
export interface RefundDto {
  id: UUID;
  orderId: UUID;
  status: RefundStatus;
  lineItems: RefundLineItemDto[];
  shippingAmount: Money;
  adjustmentAmount: Money;
  totalAmount: Money;
  reason: RefundReason;
  note: string | null;
  processedAt: ISODateString | null;
  createdAt: ISODateString;
}

/** @publish */
export interface CreateRefundDto {
  lineItems: RefundLineItemDto[];
  shippingAmount: Money;
  adjustmentAmount: Money;
  reason: RefundReason;
  note: string | null;
  notifyCustomer: boolean;
}

/** @publish */
export interface RefundListResponseDto {
  refunds: RefundDto[];
  totalRefunded: Money;
  pageInfo: PageInfo;
}

/** @publish */
export interface RefundEstimateDto {
  lineItems: RefundLineItemDto[];
  shippingAmount: Money;
  maxRefundable: Money;
  alreadyRefunded: Money;
}
