// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum ReturnStatus {
  Requested = 'requested',
  Approved = 'approved',
  Rejected = 'rejected',
  ItemsExpected = 'items_expected',
  InProgress = 'in_progress',
  Completed = 'completed',
  Cancelled = 'cancelled',
}

/** @publish */
export enum ReturnItemCondition {
  Unopened = 'unopened',
  LikeNew = 'like_new',
  Good = 'good',
  Fair = 'fair',
  Poor = 'poor',
  Damaged = 'damaged',
}

/** @publish */
export enum ReturnResolution {
  Refund = 'refund',
  Exchange = 'exchange',
  StoreCredit = 'store_credit',
  Repair = 'repair',
}

/** @publish */
export interface ReturnLineItemDto {
  lineItemId: UUID;
  quantity: number;
  reason: RefundReason;
  condition: ReturnItemCondition;
  note: string | null;
}

/** @publish */
export interface ReturnDto {
  id: UUID;
  orderId: UUID;
  status: ReturnStatus;
  lineItems: ReturnLineItemDto[];
  resolution: ReturnResolution;
  refundId: UUID | null;
  rmaNumber: string;
  shippingLabel: string | null;
  receivedAt: ISODateString | null;
  completedAt: ISODateString | null;
  createdAt: ISODateString;
}

/** @publish */
export interface CreateReturnDto {
  orderId: UUID;
  lineItems: ReturnLineItemDto[];
  resolution: ReturnResolution;
  note: string | null;
}

/** @publish */
export interface ApproveReturnDto {
  sendShippingLabel: boolean;
  note: string | null;
}

/** @publish */
export interface CompleteReturnDto {
  items: Array<{ lineItemId: UUID; receivedQuantity: number; condition: ReturnItemCondition }>;
  note: string | null;
}

/** @publish */
export interface ReturnListResponseDto {
  returns: ReturnDto[];
  pageInfo: PageInfo;
}
