// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum ShipmentStatus {
  Pending = 'pending',
  Processing = 'processing',
  InTransit = 'in_transit',
  OutForDelivery = 'out_for_delivery',
  Delivered = 'delivered',
  Failed = 'failed',
  Returned = 'returned',
  Cancelled = 'cancelled',
}

/** @publish */
export enum ShipmentPriority {
  Standard = 'standard',
  Express = 'express',
  Overnight = 'overnight',
  SameDay = 'same_day',
  Economy = 'economy',
}

/** @publish */
export interface ShipmentDto {
  id: UUID;
  orderId: UUID;
  fulfillmentId: UUID;
  status: ShipmentStatus;
  priority: ShipmentPriority;
  carrier: string;
  service: string;
  trackingNumber: string;
  trackingUrl: string | null;
  weight: ProductWeight;
  dimensions: ProductDimensions | null;
  shippedAt: ISODateString | null;
  estimatedDelivery: ISODateString | null;
  deliveredAt: ISODateString | null;
  shippingAddress: Address;
  cost: Money;
  labelUrl: string | null;
}

/** @publish */
export interface RateDto {
  carrier: string;
  service: string;
  price: Money;
  currency: Currency;
  estimatedDays: number | null;
  priority: ShipmentPriority;
}

/** @publish */
export interface GetRatesDto {
  weight: ProductWeight;
  dimensions: ProductDimensions | null;
  fromAddress: Address;
  toAddress: Address;
  priority: ShipmentPriority | null;
}

/** @publish */
export interface GetRatesResponseDto {
  rates: RateDto[];
  currency: Currency;
}

/** @publish */
export interface CreateLabelDto {
  shipmentId: UUID;
  rate: RateDto;
}

/** @publish */
export interface ShipmentEventDto {
  id: UUID;
  shipmentId: UUID;
  status: ShipmentStatus;
  location: string | null;
  message: string | null;
  timestamp: ISODateString;
}
