// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export type UUID = string;

/** @publish */
export type ISODateString = string;

/** @publish */
export type Currency = 'USD' | 'EUR' | 'GBP' | 'JPY' | 'CAD' | 'AUD' | 'CHF' | 'SEK' | 'NOK' | 'DKK';

/** @publish */
export type Locale = string;

/** @publish */
export type Timezone = string;

/** @publish */
export type JSONValue = string | number | boolean | null | JSONObject | JSONValue[];

/** @publish */
export type JSONObject = Record<string, JSONValue>;

/** @publish */
export type EmailAddress = string;

/** @publish */
export type PhoneNumberString = string;

/** @publish */
export type Slug = string;

/** @publish */
export type Tag = string;

/** @publish */
export type ColorHex = string;

/** @publish */
export type LanguageCode = string;

/** @publish */
export type CountryCode = string;

/** @publish */
export interface Money {
  amount: number;
  currency: Currency;
  formatted: string;
  fractionDigits: number;
}

/** @publish */
export interface Address {
  line1: string;
  line2: string | null;
  city: string;
  state: string;
  postalCode: string;
  countryCode: CountryCode;
  isDefault: boolean;
  label: string | null;
}

/** @publish */
export interface PhoneNumber {
  countryCode: string;
  number: string;
  extension: string | null;
  type: 'mobile' | 'home' | 'work';
}

/** @publish */
export interface DateRange {
  from: ISODateString;
  to: ISODateString;
  inclusive: boolean;
}

/** @publish */
export interface TimeRange {
  fromHour: number;
  fromMinute: number;
  toHour: number;
  toMinute: number;
  timezone: Timezone;
}

/** @publish */
export interface GeoCoordinates {
  latitude: number;
  longitude: number;
  altitude: number | null;
  accuracy: number | null;
}

/** @publish */
export interface ApiError {
  code: string;
  message: string;
  field: string | null;
  details: string[];
  traceId: string | null;
}

/** @publish */
export interface ApiResponse<T><T> {
  data: T;
  success: boolean;
  errors: ApiError[];
  requestId: string;
  timestamp: ISODateString;
  version: string;
}

/** @publish */
export interface BulkOperationResult {
  succeeded: number;
  failed: number;
  errors: ApiError[];
  processingTimeMs: number;
}

/** @publish */
export interface AuditEntry {
  actorId: UUID;
  action: string;
  resourceType: string;
  resourceId: UUID;
  diff: JSONObject;
  timestamp: ISODateString;
  ipAddress: string;
  userAgent: string;
}

/** @publish */
export interface Webhook {
  id: UUID;
  url: string;
  secret: string;
  events: string[];
  active: boolean;
  createdAt: ISODateString;
  retryPolicy: JSONObject;
}

/** @publish */
export interface FeatureFlag {
  key: string;
  enabled: boolean;
  rolloutPct: number;
  audiences: string[];
}

/** @publish */
export interface AppConfig {
  key: string;
  value: JSONValue;
  environment: string;
  description: string;
  updatedAt: ISODateString;
}
