// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export type EventType = string;

/** @publish */
export type EventVersion = 'v1' | 'v2' | 'v3';

/** @publish */
export interface DomainEvent<T><T> {
  id: UUID;
  type: EventType;
  version: EventVersion;
  payload: T;
  aggregateId: UUID;
  aggregateType: string;
  occurredAt: ISODateString;
  correlationId: UUID;
  causationId: UUID | null;
}

/** @publish */
export interface EventMetadata {
  source: string;
  environment: string;
  userId: UUID | null;
  sessionId: string | null;
  traceId: string;
}

/** @publish */
export interface EventEnvelope<T><T> {
  event: DomainEvent<T>;
  metadata: EventMetadata;
  attempt: number;
  deliveredAt: ISODateString | null;
}
