// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export type TranslationKey = string;

/** @publish */
export interface TranslatedField {
  value: string;
  locale: Locale;
  verified: boolean;
  updatedAt: ISODateString;
}

/** @publish */
export interface MultiLocaleField {
  default: string;
  translations: Record<string, TranslatedField>;
}

/** @publish */
export interface LocaleConfig {
  code: Locale;
  name: string;
  nativeName: string;
  rtl: boolean;
  dateFormat: string;
  numberFormat: JSONObject;
}
