// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum MediaType {
  Image = 'image',
  Video = 'video',
  Document = 'document',
  Audio = 'audio',
  Archive = 'archive',
  Spreadsheet = 'spreadsheet',
  Presentation = 'presentation',
}

/** @publish */
export enum ImageFormat {
  JPEG = 'jpeg',
  PNG = 'png',
  WebP = 'webp',
  GIF = 'gif',
  SVG = 'svg',
  AVIF = 'avif',
  HEIC = 'heic',
}

/** @publish */
export enum VideoCodec {
  H264 = 'h264',
  H265 = 'h265',
  VP9 = 'vp9',
  AV1 = 'av1',
}

/** @publish */
export interface ImageVariant {
  width: number;
  height: number;
  url: string;
  format: ImageFormat;
  sizeBytes: number;
  quality: number;
}

/** @publish */
export interface ImageDto {
  id: UUID;
  url: string;
  altText: string | null;
  width: number;
  height: number;
  format: ImageFormat;
  variants: ImageVariant[];
  createdAt: ISODateString;
  hash: string;
}

/** @publish */
export interface VideoDto {
  id: UUID;
  url: string;
  thumbnailUrl: string;
  durationSeconds: number;
  width: number;
  height: number;
  sizeBytes: number;
  mimeType: string;
  codec: VideoCodec;
  fps: number;
}

/** @publish */
export interface DocumentDto {
  id: UUID;
  url: string;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  pageCount: number | null;
  textExtracted: boolean;
}

/** @publish */
export interface AudioDto {
  id: UUID;
  url: string;
  durationSeconds: number;
  sizeBytes: number;
  mimeType: string;
  bitrate: number;
  sampleRate: number;
}

/** @publish */
export interface MediaAttachment {
  id: UUID;
  type: MediaType;
  url: string;
  caption: string | null;
  sortOrder: number;
  metadata: JSONObject;
}

/** @publish */
export interface MediaUploadRequest {
  filename: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
}

/** @publish */
export interface MediaUploadResponse {
  uploadUrl: string;
  mediaId: UUID;
  expiresAt: ISODateString;
  headers: Record<string, string>;
}
