// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export type SortOrder = 'asc' | 'desc';

/** @publish */
export type CursorToken = string;

/** @publish */
export interface PageInfo {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
}

/** @publish */
export interface CursorPageInfo {
  cursor: CursorToken | null;
  hasNext: boolean;
  count: number;
  totalEstimate: number | null;
}

/** @publish */
export interface SortField {
  field: string;
  order: SortOrder;
  nullsFirst: boolean;
}

/** @publish */
export interface PaginationInput {
  page: number;
  pageSize: number;
  sort: SortField[];
  cursor: CursorToken | null;
}

/** @publish */
export interface PaginatedResponse<T><T> {
  items: T[];
  pageInfo: PageInfo;
  sort: SortField | null;
}

/** @publish */
export interface CursorResponse<T><T> {
  edges: T[];
  pageInfo: CursorPageInfo;
}

/** @publish */
export interface FilterOp {
  field: string;
  operator: string;
  value: unknown;
}

/** @publish */
export interface FilterGroup {
  combinator: 'and' | 'or';
  filters: FilterOp[];
  groups: FilterGroup[];
}
