import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { emit } from '../../src/core/emitter';
import type { ExtractionResult } from '../../src/core/extractor';

function mockExtraction(fileNames: string[]): ExtractionResult {
  return {
    files: fileNames.map((fileName) => ({
      originalPath: `/project/src/${fileName}`,
      fileName,
      content: `export interface Foo { id: string; }\n`,
    })),
    exportedNames: ['Foo'],
    diagnostics: [],
  };
}

describe('emit', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'typeship-emit-'));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('writes source files and barrel to outDir/src/', () => {
    const result = emit(mockExtraction(['user.dto.d.ts']), { outDir: tmpDir });
    expect(result.files.length).toBe(2); // 1 file + barrel
    expect(result.files.some((f) => f.path.endsWith('index.d.ts'))).toBe(true);
    expect(result.files.some((f) => f.path.endsWith('user.dto.d.ts'))).toBe(true);
  });

  it('barrel contains export for each file', () => {
    const result = emit(mockExtraction(['user.dto.d.ts', 'product.dto.d.ts']), { outDir: tmpDir });
    const barrel = result.files.find((f) => f.path.endsWith('index.d.ts'));
    expect(barrel?.content).toContain("export * from './user.dto.js'");
    expect(barrel?.content).toContain("export * from './product.dto.js'");
  });

  it('dry run does not write files', () => {
    const result = emit(mockExtraction(['user.dto.ts']), { outDir: tmpDir, dryRun: true });
    // Should return files list without throwing
    expect(result.files.length).toBeGreaterThan(0);
    // outDir/src should not exist (nothing written)
    expect(existsSync(join(tmpDir, 'src'))).toBe(false);
  });
});

describe('emit – outputGrouping', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'typeship-emit-grouping-'));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  function mockExtractionWithPaths(entries: { fileName: string; originalPath: string }[]): ExtractionResult {
    return {
      files: entries.map(({ fileName, originalPath }) => ({
        originalPath,
        fileName,
        content: `// This file was auto-generated by typeship. Do not edit manually.\n\nexport interface ${fileName.replace(/[^a-zA-Z]/g, '')} { id: string; }\n`,
      })),
      exportedNames: entries.map((e) => e.fileName.replace(/[^a-zA-Z]/g, '')),
      diagnostics: [],
    };
  }

  it('"single" mode merges all declarations into index.d.ts with no separate barrel', () => {
    const extraction = mockExtractionWithPaths([
      { fileName: 'user.d.ts', originalPath: '/project/src/users/user.ts' },
      { fileName: 'product.d.ts', originalPath: '/project/src/products/product.ts' },
    ]);
    const result = emit(extraction, { outDir: tmpDir, outputGrouping: 'single' });
    expect(result.files).toHaveLength(1);
    expect(result.files[0]?.path).toMatch(/index\.d\.ts$/);
    expect(result.files[0]?.content).toContain('userdts');
    expect(result.files[0]?.content).toContain('productdts');
    // barrelPath should point to the same index.d.ts
    expect(result.barrelPath).toBe(result.files[0]?.path);
  });

  it('"single" mode index.d.ts has only one auto-generated header', () => {
    const extraction = mockExtractionWithPaths([
      { fileName: 'a.d.ts', originalPath: '/project/src/a.ts' },
      { fileName: 'b.d.ts', originalPath: '/project/src/b.ts' },
    ]);
    const result = emit(extraction, { outDir: tmpDir, outputGrouping: 'single' });
    const content = result.files[0]?.content ?? '';
    const headerCount = (content.match(/auto-generated by typeship/g) ?? []).length;
    expect(headerCount).toBe(1);
  });

  it('Record mode groups files matching patterns into named output files', () => {
    const extraction = mockExtractionWithPaths([
      { fileName: 'user.d.ts', originalPath: '/project/src/users/user.ts' },
      { fileName: 'product.d.ts', originalPath: '/project/src/products/product.ts' },
    ]);
    const result = emit(extraction, {
      outDir: tmpDir,
      outputGrouping: {
        'users.d.ts': ['**/users/**'],
        'products.d.ts': ['**/products/**'],
      },
    });
    const fileNames = result.files.map((f) => f.path.split('/').pop());
    expect(fileNames).toContain('users.d.ts');
    expect(fileNames).toContain('products.d.ts');
    expect(fileNames).toContain('index.d.ts');
  });

  it('Record mode barrel re-exports from all grouped output files', () => {
    const extraction = mockExtractionWithPaths([
      { fileName: 'user.d.ts', originalPath: '/project/src/users/user.ts' },
      { fileName: 'product.d.ts', originalPath: '/project/src/products/product.ts' },
    ]);
    const result = emit(extraction, {
      outDir: tmpDir,
      outputGrouping: {
        'users.d.ts': ['**/users/**'],
        'products.d.ts': ['**/products/**'],
      },
    });
    const barrel = result.files.find((f) => f.path.endsWith('index.d.ts'));
    expect(barrel?.content).toContain("export * from './users.js'");
    expect(barrel?.content).toContain("export * from './products.js'");
  });

  it('Record mode emits unmatched files per-file as fallback', () => {
    const extraction = mockExtractionWithPaths([
      { fileName: 'user.d.ts', originalPath: '/project/src/users/user.ts' },
      { fileName: 'misc.d.ts', originalPath: '/project/src/misc/misc.ts' },
    ]);
    const result = emit(extraction, {
      outDir: tmpDir,
      outputGrouping: { 'users.d.ts': ['**/users/**'] },
    });
    const fileNames = result.files.map((f) => f.path.split('/').pop());
    expect(fileNames).toContain('users.d.ts');
    expect(fileNames).toContain('misc.d.ts'); // fallback per-file
  });

  it('"per-file" mode (explicit) behaves identically to default', () => {
    const extraction = mockExtractionWithPaths([
      { fileName: 'user.d.ts', originalPath: '/project/src/user.ts' },
    ]);
    const defaultResult = emit(extraction, { outDir: tmpDir, dryRun: true });
    const perFileResult = emit(extraction, { outDir: tmpDir, outputGrouping: 'per-file', dryRun: true });
    expect(perFileResult.files.map((f) => f.path)).toEqual(defaultResult.files.map((f) => f.path));
  });
});
