// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { DashboardWidgetType } from './enums.js';
import { UUID, ISODateString, DateRange } from '../shared/common.js';

/** @publish */
export interface WidgetLayoutDto {
  x: number;
  y: number;
  width: number;
  height: number;
}
/** @publish */
export interface DashboardWidgetDto {
  id: UUID;
  dashboardId: UUID;
  type: DashboardWidgetType;
  title: string;
  metricId: UUID | null;
  config: Record<string,string>;
  layout: WidgetLayoutDto;
  refreshIntervalSeconds: number | null;
}
/** @publish */
export interface DashboardDto {
  id: UUID;
  name: string;
  description: string | null;
  widgets: DashboardWidgetDto[];
  isDefault: boolean;
  isPublic: boolean;
  ownerId: UUID;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}
/** @publish */
export interface CreateDashboardDto {
  name: string;
  description: string | null;
  isDefault: boolean;
  isPublic: boolean;
}
/** @publish */
export interface AddWidgetDto {
  type: DashboardWidgetType;
  title: string;
  metricId: UUID | null;
  config: Record<string,string>;
  layout: WidgetLayoutDto;
}
/** @publish */
export interface SummaryKpiDto {
  label: string;
  value: number;
  unit: string;
  change: number;
  changePct: number;
  trend: 'up' | 'down' | 'flat';
  period: DateRange;
}
/** @publish */
export interface DashboardSummaryDto {
  revenue: SummaryKpiDto;
  orders: SummaryKpiDto;
  customers: SummaryKpiDto;
  conversion: SummaryKpiDto;
  aov: SummaryKpiDto;
  refundRate: SummaryKpiDto;
}
