// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum MetricType {
  Counter = 'counter',
  Gauge = 'gauge',
  Histogram = 'histogram',
  Summary = 'summary',
}

/** @publish */
export enum Granularity {
  Minute = 'minute',
  Hour = 'hour',
  Day = 'day',
  Week = 'week',
  Month = 'month',
  Quarter = 'quarter',
  Year = 'year',
}

/** @publish */
export enum ReportStatus {
  Queued = 'queued',
  Running = 'running',
  Completed = 'completed',
  Failed = 'failed',
  Cancelled = 'cancelled',
}

/** @publish */
export enum ReportFormat {
  JSON = 'json',
  CSV = 'csv',
  XLSX = 'xlsx',
  PDF = 'pdf',
}

/** @publish */
export enum DashboardWidgetType {
  Counter = 'counter',
  LineChart = 'line_chart',
  BarChart = 'bar_chart',
  PieChart = 'pie_chart',
  Table = 'table',
  Funnel = 'funnel',
  Heatmap = 'heatmap',
}
