// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { MetricType, Granularity } from './enums.js';
import { UUID, ISODateString, DateRange } from '../shared/common.js';

/** @publish */
export interface MetricDataPointDto {
  timestamp: ISODateString;
  value: number;
  label: string | null;
}
/** @publish */
export interface MetricDto {
  id: UUID;
  name: string;
  type: MetricType;
  unit: string;
  description: string;
  dataPoints: MetricDataPointDto[];
  granularity: Granularity;
  period: DateRange;
}
/** @publish */
export interface MetricQueryDto {
  metricIds: UUID[];
  granularity: Granularity;
  dateRange: DateRange;
  filters: Record<string,string>;
}
/** @publish */
export interface AggregationDto {
  count: number;
  sum: number;
  avg: number;
  min: number;
  max: number;
  p50: number;
  p95: number;
  p99: number;
}
/** @publish */
export interface FunnelStepDto {
  name: string;
  count: number;
  conversionRate: number;
  dropOffRate: number;
}
/** @publish */
export interface FunnelDto {
  name: string;
  steps: FunnelStepDto[];
  overallConversion: number;
  period: DateRange;
}
