// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ReportStatus, ReportFormat, Granularity } from './enums.js';
import { UUID, ISODateString, DateRange } from '../shared/common.js';

/** @publish */
export interface ReportScheduleDto {
  cron: string;
  timezone: string;
  recipients: string[];
  format: ReportFormat;
}
/** @publish */
export interface ReportDto {
  id: UUID;
  name: string;
  description: string;
  status: ReportStatus;
  format: ReportFormat;
  parameters: Record<string,string>;
  downloadUrl: string | null;
  sizeBytes: number | null;
  rowCount: number | null;
  schedule: ReportScheduleDto | null;
  createdBy: UUID;
  createdAt: ISODateString;
  completedAt: ISODateString | null;
}
/** @publish */
export interface CreateReportDto {
  name: string;
  type: string;
  format: ReportFormat;
  dateRange: DateRange;
  granularity: Granularity;
  filters: Record<string,string>;
  schedule: ReportScheduleDto | null;
}
/** @publish */
export interface ReportFilterDto {
  status: ReportStatus | null;
  createdBy: UUID | null;
  dateRange: DateRange | null;
}
