// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum EmailStatus {
  Queued = 'queued',
  Sending = 'sending',
  Delivered = 'delivered',
  Opened = 'opened',
  Clicked = 'clicked',
  Bounced = 'bounced',
  Complained = 'complained',
  Failed = 'failed',
}

/** @publish */
export interface EmailRecipientDto {
  email: EmailAddress;
  name: string | null;
  substitutions: Record<string, string>;
}

/** @publish */
export interface EmailAttachmentDto {
  filename: string;
  content: string;
  contentType: string;
  disposition: 'attachment' | 'inline';
  contentId: string | null;
}

/** @publish */
export interface SendEmailDto {
  to: EmailRecipientDto[];
  cc: EmailRecipientDto[] | null;
  bcc: EmailRecipientDto[] | null;
  from: EmailRecipientDto;
  replyTo: EmailAddress | null;
  subject: string;
  templateId: string | null;
  html: string | null;
  text: string | null;
  attachments: EmailAttachmentDto[];
  headers: Record<string, string>;
  sendAt: ISODateString | null;
  trackOpens: boolean;
  trackClicks: boolean;
  tags: string[];
}

/** @publish */
export interface EmailLogDto {
  id: UUID;
  to: EmailAddress;
  subject: string;
  status: EmailStatus;
  templateId: string | null;
  openedAt: ISODateString | null;
  clickedAt: ISODateString | null;
  bouncedAt: ISODateString | null;
  sentAt: ISODateString | null;
  createdAt: ISODateString;
}

/** @publish */
export interface EmailTemplateDto {
  id: UUID;
  name: string;
  subject: string;
  html: string;
  text: string | null;
  variables: string[];
  active: boolean;
  createdAt: ISODateString;
}

/** @publish */
export interface EmailListResponseDto {
  emails: EmailLogDto[];
  pageInfo: PageInfo;
}
