// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum NotificationStatus {
  Unread = 'unread',
  Read = 'read',
  Archived = 'archived',
  Deleted = 'deleted',
}

/** @publish */
export enum NotificationPriority {
  Low = 'low',
  Normal = 'normal',
  High = 'high',
  Urgent = 'urgent',
}

/** @publish */
export interface NotificationActionDto {
  label: string;
  url: string;
  style: 'primary' | 'secondary' | 'danger';
}

/** @publish */
export interface NotificationDto {
  id: UUID;
  userId: UUID;
  type: string;
  status: NotificationStatus;
  priority: NotificationPriority;
  title: string;
  body: string;
  imageUrl: string | null;
  actions: NotificationActionDto[];
  resourceType: string | null;
  resourceId: UUID | null;
  metadata: JSONObject;
  readAt: ISODateString | null;
  expiresAt: ISODateString | null;
  createdAt: ISODateString;
}

/** @publish */
export interface NotificationListResponseDto {
  notifications: NotificationDto[];
  unreadCount: number;
  pageInfo: PageInfo;
}

/** @publish */
export interface MarkNotificationsReadDto {
  ids: UUID[];
  all: boolean;
}

/** @publish */
export interface DeleteNotificationsDto {
  ids: UUID[];
  all: boolean;
}
