// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum PushPlatform {
  iOS = 'ios',
  Android = 'android',
  Web = 'web',
}

/** @publish */
export interface PushDeviceDto {
  id: UUID;
  userId: UUID;
  token: string;
  platform: PushPlatform;
  deviceModel: string | null;
  osVersion: string | null;
  appVersion: string | null;
  timezone: Timezone;
  locale: Locale;
  active: boolean;
  registeredAt: ISODateString;
}

/** @publish */
export interface SendPushDto {
  userIds: UUID[];
  deviceIds: UUID[] | null;
  title: string;
  body: string;
  imageUrl: string | null;
  data: JSONObject;
  badge: number | null;
  sound: string | null;
  priority: 'normal' | 'high';
  ttl: number | null;
  collapseKey: string | null;
  sendAt: ISODateString | null;
}

/** @publish */
export interface PushLogDto {
  id: UUID;
  deviceId: UUID;
  title: string;
  body: string;
  status: 'sent' | 'delivered' | 'failed' | 'clicked';
  sentAt: ISODateString;
  deliveredAt: ISODateString | null;
  clickedAt: ISODateString | null;
  failureReason: string | null;
}

/** @publish */
export interface RegisterDeviceDto {
  token: string;
  platform: PushPlatform;
  deviceModel: string | null;
  osVersion: string | null;
  appVersion: string | null;
  timezone: Timezone;
  locale: Locale;
}

/** @publish */
export interface UnregisterDeviceDto {
  deviceId: UUID;
}
