// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum WebhookEventCategory {
  Order = 'order',
  Payment = 'payment',
  Product = 'product',
  Customer = 'customer',
  Fulfillment = 'fulfillment',
  Review = 'review',
  Subscription = 'subscription',
}

/** @publish */
export enum WebhookDeliveryStatus {
  Pending = 'pending',
  Success = 'success',
  Failed = 'failed',
  Retrying = 'retrying',
  Exhausted = 'exhausted',
}

/** @publish */
export interface WebhookEndpointDto {
  id: UUID;
  url: string;
  description: string | null;
  events: string[];
  signingSecret: string;
  active: boolean;
  retryPolicy: JSONObject;
  metadata: JSONObject;
  createdAt: ISODateString;
}

/** @publish */
export interface CreateWebhookEndpointDto {
  url: string;
  description: string | null;
  events: string[];
  active: boolean;
  metadata: JSONObject | null;
}

/** @publish */
export interface WebhookDeliveryDto {
  id: UUID;
  endpointId: UUID;
  eventType: string;
  status: WebhookDeliveryStatus;
  requestBody: string;
  responseStatus: number | null;
  responseBody: string | null;
  attempt: number;
  duration: number | null;
  createdAt: ISODateString;
  nextRetryAt: ISODateString | null;
}

/** @publish */
export interface RetryWebhookDto {
  deliveryId: UUID;
}

/** @publish */
export interface WebhookDeliveryListResponseDto {
  deliveries: WebhookDeliveryDto[];
  pageInfo: PageInfo;
}

/** @publish */
export interface WebhookTestDto {
  endpointId: UUID;
  eventType: string;
  samplePayload: JSONObject | null;
}
