// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { UserRole, AuthProvider, TwoFactorMethod } from './enums.js';
import { Locale, Timezone } from '../shared/common.js';

/** @publish */
export interface CreateUserDto {
  email: string;
  username: string;
  firstName: string;
  lastName: string;
  password: string;
  role: UserRole;
  provider: AuthProvider;
  locale: Locale;
  timezone: Timezone;
}
/** @publish */
export interface RegisterDto {
  email: string;
  username: string;
  firstName: string;
  lastName: string;
  password: string;
  confirmPassword: string;
  acceptTerms: boolean;
  locale: Locale;
}
/** @publish */
export interface InviteUserDto {
  email: string;
  role: UserRole;
  message: string | null;
  expiresInHours: number;
}
/** @publish */
export interface EnableTwoFactorDto {
  method: TwoFactorMethod;
  phoneNumber: string | null;
}
/** @publish */
export interface VerifyTwoFactorDto {
  code: string;
  method: TwoFactorMethod;
  trustDevice: boolean;
}
/** @publish */
export interface CreateApiKeyDto {
  name: string;
  permissions: string[];
  expiresAt: ISODateString | null;
}
