// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum UserRole {
  SuperAdmin = 'super_admin',
  Admin = 'admin',
  Manager = 'manager',
  Editor = 'editor',
  Viewer = 'viewer',
  Guest = 'guest',
}

/** @publish */
export enum UserStatus {
  Active = 'active',
  Inactive = 'inactive',
  Suspended = 'suspended',
  PendingVerification = 'pending_verification',
  PendingDeletion = 'pending_deletion',
  Deleted = 'deleted',
}

/** @publish */
export enum AuthProvider {
  Email = 'email',
  Google = 'google',
  GitHub = 'github',
  Microsoft = 'microsoft',
  Apple = 'apple',
  SAML = 'saml',
}

/** @publish */
export enum TwoFactorMethod {
  TOTP = 'totp',
  SMS = 'sms',
  Email = 'email',
  BackupCode = 'backup_code',
}

/** @publish */
export enum SessionStatus {
  Active = 'active',
  Revoked = 'revoked',
  Expired = 'expired',
}

/** @publish */
export enum PermissionAction {
  Create = 'create',
  Read = 'read',
  Update = 'update',
  Delete = 'delete',
  Manage = 'manage',
}
