// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { UserRole, UserStatus } from './enums.js';
import { Locale, Timezone } from '../shared/common.js';

/** @publish */
export interface UpdateUserDto {
  firstName: string | null;
  lastName: string | null;
  username: string | null;
  role: UserRole | null;
  status: UserStatus | null;
  locale: Locale | null;
  timezone: Timezone | null;
}
/** @publish */
export interface UpdateProfileDto {
  displayName: string | null;
  bio: string | null;
  website: string | null;
  location: string | null;
  pronouns: string | null;
}
/** @publish */
export interface ChangePasswordDto {
  currentPassword: string;
  newPassword: string;
  confirmPassword: string;
  revokeOtherSessions: boolean;
}
/** @publish */
export interface ForgotPasswordDto {
  email: string;
}
/** @publish */
export interface ResetPasswordDto {
  token: string;
  newPassword: string;
  confirmPassword: string;
}
/** @publish */
export interface VerifyEmailDto {
  token: string;
}
/** @publish */
export interface UpdateNotificationPrefsDto {
  emailMarketing: boolean;
  emailTransactional: boolean;
  emailSecurity: boolean;
  pushEnabled: boolean;
  smsEnabled: boolean;
  digestFrequency: 'daily' | 'weekly' | 'never';
}
