// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { UserDto, UserSummaryDto, UserSessionDto, UserPermissionDto } from './user.dto.js';
import { UserRole, UserStatus } from './enums.js';
import { PageInfo, SortField } from '../shared/pagination.js';
import { ISODateString, DateRange } from '../shared/common.js';

/** @publish */
export interface UserListResponse {
  items: UserDto[];
  pageInfo: PageInfo;
  sort: SortField | null;
}
/** @publish */
export interface UserDetailResponse {
  user: UserDto;
  sessions: UserSessionDto[];
  permissions: UserPermissionDto[];
}
/** @publish */
export interface UserFilterDto {
  search: string | null;
  role: UserRole | null;
  status: UserStatus | null;
  provider: string | null;
  emailVerified: boolean | null;
  createdIn: DateRange | null;
}
/** @publish */
export interface UserStatsDto {
  total: number;
  active: number;
  suspended: number;
  pendingVerification: number;
  newThisMonth: number;
  newThisWeek: number;
  byRole: Record<string,number>;
  byProvider: Record<string,number>;
}
/** @publish */
export interface ApiKeyDto {
  id: string;
  name: string;
  keyPrefix: string;
  permissions: string[];
  lastUsedAt: ISODateString | null;
  expiresAt: ISODateString | null;
  createdAt: ISODateString;
}
/** @publish */
export interface AuditLogFilterDto {
  actorId: string | null;
  resourceType: string | null;
  action: string | null;
  dateRange: DateRange | null;
}
