// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { UserRole, UserStatus, AuthProvider } from './enums.js';
import { UUID, ISODateString, Locale, Timezone } from '../shared/common.js';
import { ImageDto } from '../shared/media.js';

/** @publish */
export interface UserDto {
  id: UUID;
  email: string;
  username: string;
  firstName: string;
  lastName: string;
  displayName: string;
  role: UserRole;
  status: UserStatus;
  provider: AuthProvider;
  avatar: ImageDto | null;
  emailVerified: boolean;
  twoFactorEnabled: boolean;
  locale: Locale;
  timezone: Timezone;
  lastLoginAt: ISODateString | null;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}
/** @publish */
export interface UserSummaryDto {
  id: UUID;
  displayName: string;
  email: string;
  avatar: ImageDto | null;
  role: UserRole;
}
/** @publish */
export interface UserSessionDto {
  id: UUID;
  userId: UUID;
  deviceName: string;
  deviceType: string;
  ipAddress: string;
  location: string | null;
  createdAt: ISODateString;
  lastActiveAt: ISODateString;
  expiresAt: ISODateString;
}
/** @publish */
export interface UserPermissionDto {
  id: UUID;
  action: string;
  resource: string;
  conditions: Record<string,string>;
}
/** @publish */
export interface UserRoleAssignmentDto {
  userId: UUID;
  role: UserRole;
  assignedBy: UUID;
  assignedAt: ISODateString;
  expiresAt: ISODateString | null;
}
