// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum NotificationType {
  OrderConfirmed = 'order_confirmed',
  OrderShipped = 'order_shipped',
  OrderDelivered = 'order_delivered',
  OrderCancelled = 'order_cancelled',
  PaymentSucceeded = 'payment_succeeded',
  PaymentFailed = 'payment_failed',
  RefundProcessed = 'refund_processed',
  LowStock = 'low_stock',
  UserRegistered = 'user_registered',
  PasswordReset = 'password_reset',
  InviteAccepted = 'invite_accepted',
  ReviewPosted = 'review_posted',
  PromotionLaunched = 'promotion_launched',
  SystemAlert = 'system_alert',
}

/** @publish */
export enum NotificationStatus {
  Pending = 'pending',
  Sent = 'sent',
  Delivered = 'delivered',
  Failed = 'failed',
  Bounced = 'bounced',
  Read = 'read',
  Dismissed = 'dismissed',
}

/** @publish */
export enum NotificationChannel {
  Email = 'email',
  SMS = 'sms',
  Push = 'push',
  InApp = 'in_app',
  Webhook = 'webhook',
  Slack = 'slack',
}

/** @publish */
export enum NotificationPriority {
  Low = 'low',
  Normal = 'normal',
  High = 'high',
  Critical = 'critical',
}
