// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { NotificationDto, NotificationSummaryDto } from './notification.dto.js';
import { NotificationType, NotificationStatus, NotificationChannel } from './enums.js';
import { PageInfo } from '../shared/pagination.js';
import { DateRange } from '../shared/common.js';

/** @publish */
export interface NotificationListResponse {
  items: NotificationSummaryDto[];
  pageInfo: PageInfo;
  unreadCount: number;
}
/** @publish */
export interface NotificationDetailResponse {
  notification: NotificationDto;
}
/** @publish */
export interface NotificationFilterDto {
  userId: string | null;
  type: NotificationType | null;
  status: NotificationStatus | null;
  channel: NotificationChannel | null;
  isRead: boolean | null;
  dateRange: DateRange | null;
}
/** @publish */
export interface NotificationStatsDto {
  totalSent: number;
  delivered: number;
  failed: number;
  deliveryRate: number;
  byType: Record<string,number>;
  byChannel: Record<string,number>;
}
/** @publish */
export interface NotificationPreferencesDto {
  userId: string;
  byType: Record<string,string[]>;
  quietHoursEnabled: boolean;
  quietHoursStart: string | null;
  quietHoursEnd: string | null;
  timezone: string;
}
