// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { NotificationType, NotificationStatus, NotificationChannel, NotificationPriority } from './enums.js';
import { UUID, ISODateString } from '../shared/common.js';

/** @publish */
export interface NotificationDto {
  id: UUID;
  userId: UUID;
  type: NotificationType;
  channel: NotificationChannel;
  status: NotificationStatus;
  priority: NotificationPriority;
  subject: string | null;
  body: string;
  data: Record<string,string>;
  readAt: ISODateString | null;
  sentAt: ISODateString | null;
  createdAt: ISODateString;
}
/** @publish */
export interface NotificationSummaryDto {
  id: UUID;
  type: NotificationType;
  subject: string | null;
  isRead: boolean;
  createdAt: ISODateString;
}
/** @publish */
export interface CreateNotificationDto {
  userId: UUID;
  type: NotificationType;
  channels: NotificationChannel[];
  priority: NotificationPriority;
  data: Record<string,string>;
  scheduledAt: ISODateString | null;
}
/** @publish */
export interface BulkNotificationDto {
  userIds: UUID[];
  type: NotificationType;
  channels: NotificationChannel[];
  priority: NotificationPriority;
  data: Record<string,string>;
}
