// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { NotificationType, NotificationChannel } from './enums.js';
import { UUID, ISODateString, Locale } from '../shared/common.js';

/** @publish */
export interface TemplateVariableDto {
  name: string;
  description: string;
  required: boolean;
  defaultValue: string | null;
}
/** @publish */
export interface NotificationTemplateDto {
  id: UUID;
  type: NotificationType;
  channel: NotificationChannel;
  locale: Locale;
  subject: string | null;
  body: string;
  variables: TemplateVariableDto[];
  isActive: boolean;
  version: number;
  createdAt: ISODateString;
}
/** @publish */
export interface CreateTemplateDto {
  type: NotificationType;
  channel: NotificationChannel;
  locale: Locale;
  subject: string | null;
  body: string;
}
/** @publish */
export interface UpdateTemplateDto {
  subject: string | null;
  body: string | null;
  isActive: boolean | null;
}
/** @publish */
export interface PreviewTemplateDto {
  templateId: UUID;
  variables: Record<string,string>;
}
