// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum CouponType {
  Percentage = 'percentage',
  FixedAmount = 'fixed_amount',
  FreeShipping = 'free_shipping',
  BuyXGetY = 'buy_x_get_y',
}

/** @publish */
export enum CouponStatus {
  Active = 'active',
  Inactive = 'inactive',
  Expired = 'expired',
  Depleted = 'depleted',
}

/** @publish */
export interface CouponDto {
  id: UUID;
  code: string;
  type: CouponType;
  status: CouponStatus;
  value: number;
  currency: Currency | null;
  minOrderAmount: Money | null;
  maxDiscountAmount: Money | null;
  usageLimit: number | null;
  perCustomerLimit: number | null;
  usedCount: number;
  validFrom: ISODateString;
  validUntil: ISODateString | null;
  applicableProducts: UUID[];
  applicableCategories: UUID[];
  firstTimeOnly: boolean;
  createdAt: ISODateString;
}

/** @publish */
export interface CreateCouponDto {
  code: string;
  type: CouponType;
  value: number;
  currency: Currency | null;
  minOrderAmount: Money | null;
  usageLimit: number | null;
  perCustomerLimit: number | null;
  validFrom: ISODateString;
  validUntil: ISODateString | null;
  firstTimeOnly: boolean;
}

/** @publish */
export interface ValidateCouponDto {
  code: string;
  orderId: UUID;
  customerId: UUID | null;
}

/** @publish */
export interface ValidateCouponResponseDto {
  valid: boolean;
  coupon: CouponDto | null;
  discountAmount: Money | null;
  errorCode: string | null;
  errorMessage: string | null;
}

/** @publish */
export interface CouponUsageDto {
  id: UUID;
  couponId: UUID;
  orderId: UUID;
  customerId: UUID | null;
  discountAmount: Money;
  usedAt: ISODateString;
}
