// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum InvoiceStatus {
  Draft = 'draft',
  Open = 'open',
  Paid = 'paid',
  Void = 'void',
  Uncollectible = 'uncollectible',
}

/** @publish */
export interface InvoiceLineDto {
  id: UUID;
  description: string;
  quantity: number;
  unitPrice: Money;
  discount: Money;
  tax: Money;
  total: Money;
  period: DateRange | null;
  metadata: JSONObject;
}

/** @publish */
export interface InvoiceDto {
  id: UUID;
  number: string;
  orderId: UUID | null;
  customerId: UUID;
  status: InvoiceStatus;
  currency: Currency;
  lineItems: InvoiceLineDto[];
  subtotal: Money;
  taxTotal: Money;
  discountTotal: Money;
  total: Money;
  amountDue: Money;
  amountPaid: Money;
  dueDate: ISODateString;
  paidAt: ISODateString | null;
  pdfUrl: string | null;
  note: string | null;
  createdAt: ISODateString;
}

/** @publish */
export interface CreateInvoiceDto {
  customerId: UUID;
  orderId: UUID | null;
  lineItems: InvoiceLineDto[];
  dueDate: ISODateString;
  note: string | null;
  sendEmail: boolean;
}

/** @publish */
export interface FinalizeInvoiceDto {
  sendEmail: boolean;
}

/** @publish */
export interface PayInvoiceDto {
  paymentMethodId: UUID;
  amount: Money;
}

/** @publish */
export interface InvoiceListResponseDto {
  invoices: InvoiceDto[];
  pageInfo: PageInfo;
}
