// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export interface CreatePaymentIntentDto {
  orderId: UUID;
  amount: Money;
  paymentMethodId: UUID | null;
  gateway: PaymentGateway;
  returnUrl: string | null;
  metadata: JSONObject | null;
}

/** @publish */
export interface ConfirmPaymentDto {
  paymentIntentId: UUID;
  paymentMethodId: UUID;
  savePaymentMethod: boolean;
}

/** @publish */
export interface CapturePaymentDto {
  paymentIntentId: UUID;
  amount: Money | null;
}

/** @publish */
export interface VoidPaymentDto {
  paymentIntentId: UUID;
  reason: string | null;
}

/** @publish */
export interface ChargeDto {
  id: UUID;
  orderId: UUID;
  paymentIntentId: UUID;
  amount: Money;
  captured: boolean;
  refunded: Money;
  status: PaymentIntentStatus;
  failureCode: string | null;
  failureMessage: string | null;
  receiptUrl: string | null;
  gateway: PaymentGateway;
  gatewayChargeId: string;
  createdAt: ISODateString;
}

/** @publish */
export interface ChargeListResponseDto {
  charges: ChargeDto[];
  pageInfo: PageInfo;
}

/** @publish */
export interface AddPaymentMethodDto {
  type: PaymentMethodType;
  gateway: PaymentGateway;
  token: string;
  billingAddress: Address | null;
  setAsDefault: boolean;
}

/** @publish */
export interface PaymentMethodListResponseDto {
  methods: PaymentMethodDto[];
  total: number;
}
