// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum PaymentMethodType {
  Card = 'card',
  BankTransfer = 'bank_transfer',
  Wallet = 'wallet',
  BuyNowPayLater = 'bnpl',
  Cash = 'cash',
  Check = 'check',
  Cryptocurrency = 'crypto',
  GiftCard = 'gift_card',
  StoreCredit = 'store_credit',
}

/** @publish */
export enum PaymentGateway {
  Stripe = 'stripe',
  PayPal = 'paypal',
  Braintree = 'braintree',
  Square = 'square',
  Adyen = 'adyen',
  Checkout = 'checkout',
  Klarna = 'klarna',
  Afterpay = 'afterpay',
  Manual = 'manual',
}

/** @publish */
export enum PaymentIntentStatus {
  Created = 'created',
  Processing = 'processing',
  RequiresAction = 'requires_action',
  RequiresCapture = 'requires_capture',
  Succeeded = 'succeeded',
  Cancelled = 'cancelled',
  Failed = 'failed',
}

/** @publish */
export enum CardBrand {
  Visa = 'visa',
  Mastercard = 'mastercard',
  Amex = 'amex',
  Discover = 'discover',
  JCB = 'jcb',
  DinersClub = 'diners',
  UnionPay = 'unionpay',
  Unknown = 'unknown',
}

/** @publish */
export interface CardDetailsDto {
  brand: CardBrand;
  last4: string;
  expMonth: number;
  expYear: number;
  fingerprint: string;
  funding: 'credit' | 'debit' | 'prepaid' | 'unknown';
  country: CountryCode | null;
  walletType: string | null;
}

/** @publish */
export interface BankAccountDetailsDto {
  bankName: string;
  accountType: 'checking' | 'savings';
  last4: string;
  routingNumber: string | null;
  country: CountryCode;
  currency: Currency;
}

/** @publish */
export interface PaymentMethodDto {
  id: UUID;
  type: PaymentMethodType;
  gateway: PaymentGateway;
  isDefault: boolean;
  card: CardDetailsDto | null;
  bankAccount: BankAccountDetailsDto | null;
  billingAddress: Address | null;
  expiresAt: ISODateString | null;
  createdAt: ISODateString;
}

/** @publish */
export interface PaymentIntentDto {
  id: UUID;
  gatewayIntentId: string;
  orderId: UUID;
  amount: Money;
  status: PaymentIntentStatus;
  paymentMethodId: UUID | null;
  gateway: PaymentGateway;
  clientSecret: string | null;
  nextAction: JSONObject | null;
  metadata: JSONObject;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}
