// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum PayoutStatus {
  Scheduled = 'scheduled',
  InTransit = 'in_transit',
  Paid = 'paid',
  Failed = 'failed',
  Cancelled = 'cancelled',
}

/** @publish */
export enum PayoutType {
  Standard = 'standard',
  Instant = 'instant',
}

/** @publish */
export interface PayoutDto {
  id: UUID;
  vendorId: UUID;
  amount: Money;
  status: PayoutStatus;
  type: PayoutType;
  arrivalDate: ISODateString;
  description: string | null;
  failureCode: string | null;
  failureMessage: string | null;
  createdAt: ISODateString;
}

/** @publish */
export interface CreatePayoutDto {
  vendorId: UUID;
  amount: Money;
  type: PayoutType;
  description: string | null;
}

/** @publish */
export interface PayoutListResponseDto {
  payouts: PayoutDto[];
  pageInfo: PageInfo;
  totalPaid: Money;
}

/** @publish */
export interface BankAccountDto {
  id: UUID;
  accountHolderName: string;
  bankName: string;
  accountLast4: string;
  routingNumber: string | null;
  currency: Currency;
  country: CountryCode;
  isDefault: boolean;
  verified: boolean;
  createdAt: ISODateString;
}

/** @publish */
export interface AddBankAccountDto {
  accountHolderName: string;
  routingNumber: string;
  accountNumber: string;
  accountType: 'checking' | 'savings';
  currency: Currency;
  country: CountryCode;
}
