// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum SubscriptionStatus {
  Active = 'active',
  PastDue = 'past_due',
  Unpaid = 'unpaid',
  Cancelled = 'cancelled',
  Incomplete = 'incomplete',
  Trialing = 'trialing',
  Paused = 'paused',
}

/** @publish */
export enum BillingInterval {
  Day = 'day',
  Week = 'week',
  Month = 'month',
  Year = 'year',
}

/** @publish */
export interface PlanDto {
  id: UUID;
  name: string;
  description: string;
  amount: Money;
  interval: BillingInterval;
  intervalCount: number;
  trialDays: number | null;
  features: string[];
  metadata: JSONObject;
  active: boolean;
}

/** @publish */
export interface SubscriptionItemDto {
  id: UUID;
  planId: UUID;
  quantity: number;
  unitPrice: Money;
  metadata: JSONObject;
}

/** @publish */
export interface SubscriptionDto {
  id: UUID;
  customerId: UUID;
  status: SubscriptionStatus;
  items: SubscriptionItemDto[];
  currentPeriodStart: ISODateString;
  currentPeriodEnd: ISODateString;
  trialStart: ISODateString | null;
  trialEnd: ISODateString | null;
  cancelAt: ISODateString | null;
  cancelledAt: ISODateString | null;
  pausedAt: ISODateString | null;
  defaultPaymentMethodId: UUID | null;
  metadata: JSONObject;
  createdAt: ISODateString;
}

/** @publish */
export interface CreateSubscriptionDto {
  customerId: UUID;
  planId: UUID;
  quantity: number;
  paymentMethodId: UUID;
  trialEnd: ISODateString | null;
  couponCode: string | null;
  metadata: JSONObject | null;
}

/** @publish */
export interface UpdateSubscriptionDto {
  planId: UUID | null;
  quantity: number | null;
  paymentMethodId: UUID | null;
  pauseUntil: ISODateString | null;
  cancelAt: ISODateString | null;
  cancelAtPeriodEnd: boolean | null;
}

/** @publish */
export interface SubscriptionListResponseDto {
  subscriptions: SubscriptionDto[];
  pageInfo: PageInfo;
}
