// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum PaymentStatus {
  Pending = 'pending',
  Processing = 'processing',
  Authorized = 'authorized',
  Captured = 'captured',
  Succeeded = 'succeeded',
  Failed = 'failed',
  Cancelled = 'cancelled',
  Refunded = 'refunded',
  PartiallyRefunded = 'partially_refunded',
  Disputed = 'disputed',
  DisputeLost = 'dispute_lost',
  DisputeWon = 'dispute_won',
}

/** @publish */
export enum PaymentMethod {
  Card = 'card',
  BankTransfer = 'bank_transfer',
  Wallet = 'wallet',
  CashOnDelivery = 'cash_on_delivery',
  Crypto = 'crypto',
  BNPL = 'bnpl',
  GiftCard = 'gift_card',
}

/** @publish */
export enum CardBrand {
  Visa = 'visa',
  Mastercard = 'mastercard',
  Amex = 'amex',
  Discover = 'discover',
  UnionPay = 'union_pay',
  JCB = 'jcb',
}

/** @publish */
export enum DisputeReason {
  Fraudulent = 'fraudulent',
  Duplicate = 'duplicate',
  ProductNotReceived = 'product_not_received',
  ProductUnacceptable = 'product_unacceptable',
  Unrecognized = 'unrecognized',
  SubscriptionCancelled = 'subscription_cancelled',
}

/** @publish */
export enum RefundReason {
  RequestedByCustomer = 'requested_by_customer',
  Duplicate = 'duplicate',
  Fraudulent = 'fraudulent',
  ProductNotReceived = 'product_not_received',
  Other = 'other',
}
