// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { PaymentStatus, PaymentMethod, CardBrand } from './enums.js';
import { UUID, ISODateString, Money, Currency } from '../shared/common.js';

/** @publish */
export interface CardDto {
  last4: string;
  brand: CardBrand;
  expMonth: number;
  expYear: number;
  holderName: string | null;
  fingerprint: string;
}
/** @publish */
export interface BankAccountDto {
  last4: string;
  bankName: string;
  accountType: 'checking' | 'savings';
  routingNumber: string;
}
/** @publish */
export interface PaymentDto {
  id: UUID;
  orderId: UUID;
  userId: UUID;
  amount: Money;
  status: PaymentStatus;
  method: PaymentMethod;
  currency: Currency;
  transactionId: string | null;
  processorId: string | null;
  card: CardDto | null;
  bankAccount: BankAccountDto | null;
  failureCode: string | null;
  failureMessage: string | null;
  metadata: Record<string,string>;
  capturedAt: ISODateString | null;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}
/** @publish */
export interface PaymentSummaryDto {
  id: UUID;
  amount: Money;
  status: PaymentStatus;
  method: PaymentMethod;
  createdAt: ISODateString;
}
