// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { PaymentDto, PaymentSummaryDto } from './payment.dto.js';
import { PaymentStatus, PaymentMethod } from './enums.js';
import { PageInfo } from '../shared/pagination.js';
import { Money, DateRange, Currency } from '../shared/common.js';

/** @publish */
export interface PaymentListResponse {
  items: PaymentSummaryDto[];
  pageInfo: PageInfo;
}
/** @publish */
export interface PaymentDetailResponse {
  payment: PaymentDto;
  refundedAmount: Money;
  refundableAmount: Money;
}
/** @publish */
export interface PaymentFilterDto {
  userId: string | null;
  orderId: string | null;
  status: PaymentStatus | null;
  method: PaymentMethod | null;
  currency: Currency | null;
  dateRange: DateRange | null;
  minAmount: number | null;
  maxAmount: number | null;
}
/** @publish */
export interface PaymentStatsDto {
  totalRevenue: Money;
  capturedToday: Money;
  pendingAmount: Money;
  refundedTotal: Money;
  successRate: number;
  byMethod: Record<string,number>;
  byCurrency: Record<string,Money>;
}
/** @publish */
export interface PaymentIntentDto {
  id: UUID;
  clientSecret: string;
  amount: Money;
  status: PaymentStatus;
  expiresAt: ISODateString;
}
