// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { RefundReason } from './enums.js';
import { UUID, ISODateString, Money } from '../shared/common.js';

/** @publish */
export interface RefundLineDto {
  orderLineId: UUID;
  amount: Money;
  quantity: number;
}
/** @publish */
export interface RefundDto {
  id: UUID;
  paymentId: UUID;
  orderId: UUID;
  amount: Money;
  reason: RefundReason;
  lines: RefundLineDto[];
  notes: string | null;
  status: 'pending' | 'processing' | 'succeeded' | 'failed';
  processedAt: ISODateString | null;
  createdAt: ISODateString;
}
/** @publish */
export interface CreateRefundDto {
  paymentId: UUID;
  lines: RefundLineDto[];
  reason: RefundReason;
  notes: string | null;
  notifyCustomer: boolean;
}
/** @publish */
export interface InvoiceDto {
  id: UUID;
  orderId: UUID;
  userId: UUID;
  number: string;
  subtotal: Money;
  tax: Money;
  total: Money;
  issuedAt: ISODateString;
  dueAt: ISODateString;
  paidAt: ISODateString | null;
  downloadUrl: string;
}
/** @publish */
export interface DisputeDto {
  id: UUID;
  paymentId: UUID;
  reason: string;
  amount: Money;
  status: string;
  evidence: Record<string,string>;
  dueBy: ISODateString;
  createdAt: ISODateString;
}
