// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { Carrier, ShippingServiceLevel, PackageType } from './enums.js';
import { Address } from '../shared/common.js';

/** @publish */
export interface CreateShipmentDto {
  orderId: string;
  carrier: Carrier;
  serviceLevel: ShippingServiceLevel;
  packageType: PackageType;
  weightGrams: number;
  lines: Array<{orderLineId:string;quantity:number}>;
  customsValue: number | null;
  notifyCustomer: boolean;
}
/** @publish */
export interface ShippingRateRequestDto {
  originAddress: Address;
  destinationAddress: Address;
  weightGrams: number;
  lengthCm: number;
  widthCm: number;
  heightCm: number;
  carriers: string[];
}
/** @publish */
export interface ShippingRateDto {
  carrier: string;
  serviceLevel: string;
  estimatedDays: number;
  price: number;
  currency: string;
  guaranteed: boolean;
}
/** @publish */
export interface ShippingZoneDto {
  id: string;
  name: string;
  countries: string[];
  regions: string[];
  rates: ShippingRateDto[];
}
/** @publish */
export interface UpdateTrackingDto {
  trackingNumber: string;
  carrier: string;
  trackingUrl: string | null;
}
