// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum ShipmentStatus {
  Pending = 'pending',
  ReadyToShip = 'ready_to_ship',
  PickedUp = 'picked_up',
  InTransit = 'in_transit',
  OutForDelivery = 'out_for_delivery',
  AttemptedDelivery = 'attempted_delivery',
  Delivered = 'delivered',
  Failed = 'failed',
  Returned = 'returned',
  Lost = 'lost',
}

/** @publish */
export enum Carrier {
  FedEx = 'fedex',
  UPS = 'ups',
  USPS = 'usps',
  DHL = 'dhl',
  AmazonLogistics = 'amazon_logistics',
  Local = 'local',
  SelfFulfilled = 'self_fulfilled',
}

/** @publish */
export enum ShippingServiceLevel {
  Economy = 'economy',
  Standard = 'standard',
  Express = 'express',
  Overnight = 'overnight',
  SameDay = 'same_day',
}

/** @publish */
export enum PackageType {
  Box = 'box',
  Envelope = 'envelope',
  Tube = 'tube',
  Pallet = 'pallet',
  Custom = 'custom',
}
