// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ShipmentDto } from './shipment.dto.js';
import { ShipmentStatus, Carrier } from './enums.js';
import { PageInfo } from '../shared/pagination.js';
import { DateRange } from '../shared/common.js';

/** @publish */
export interface ShipmentListResponse {
  items: ShipmentDto[];
  pageInfo: PageInfo;
}
/** @publish */
export interface ShipmentFilterDto {
  orderId: string | null;
  status: ShipmentStatus | null;
  carrier: Carrier | null;
  dateRange: DateRange | null;
}
/** @publish */
export interface ShippingStatsDto {
  totalShipments: number;
  delivered: number;
  inTransit: number;
  failed: number;
  avgDeliveryDays: number;
  byCarrier: Record<string,number>;
}
/** @publish */
export interface CarrierAccountDto {
  id: string;
  carrier: string;
  accountNumber: string;
  isDefault: boolean;
  isActive: boolean;
  capabilities: string[];
}
