// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ShipmentStatus, Carrier, ShippingServiceLevel, PackageType } from './enums.js';
import { UUID, ISODateString, Address, Money } from '../shared/common.js';

/** @publish */
export interface TrackingEventDto {
  status: string;
  description: string;
  location: string | null;
  timestamp: ISODateString;
}
/** @publish */
export interface PackageDimensionsDto {
  lengthCm: number;
  widthCm: number;
  heightCm: number;
  weightGrams: number;
}
/** @publish */
export interface ShipmentLineDto {
  orderLineId: UUID;
  productId: UUID;
  sku: string;
  quantity: number;
}
/** @publish */
export interface ShipmentDto {
  id: UUID;
  orderId: UUID;
  status: ShipmentStatus;
  carrier: Carrier;
  serviceLevel: ShippingServiceLevel;
  trackingNumber: string | null;
  trackingUrl: string | null;
  shippingAddress: Address;
  lines: ShipmentLineDto[];
  dimensions: PackageDimensionsDto | null;
  packageType: PackageType;
  shippingCost: Money;
  estimatedDelivery: ISODateString | null;
  shippedAt: ISODateString | null;
  deliveredAt: ISODateString | null;
  events: TrackingEventDto[];
  createdAt: ISODateString;
}
