// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export interface DashboardWidgetDto {
  id: UUID;
  type: string;
  title: string;
  config: JSONObject;
  data: JSONValue | null;
  position: number;
  size: 'sm' | 'md' | 'lg' | 'xl';
  lastRefreshed: ISODateString | null;
}

/** @publish */
export interface DashboardDto {
  id: UUID;
  name: string;
  userId: UUID;
  widgets: DashboardWidgetDto[];
  isDefault: boolean;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

/** @publish */
export interface CreateDashboardDto {
  name: string;
  isDefault: boolean;
}

/** @publish */
export interface UpdateDashboardDto {
  name: string | null;
  widgets: DashboardWidgetDto[] | null;
  isDefault: boolean | null;
}

/** @publish */
export interface AddWidgetDto {
  type: string;
  title: string;
  config: JSONObject;
  size: 'sm' | 'md' | 'lg' | 'xl';
}

/** @publish */
export interface WidgetDataRequestDto {
  widgetId: UUID;
  dateRange: DateRange;
  filters: JSONObject;
}

/** @publish */
export interface KpiDto {
  label: string;
  value: number | string;
  unit: string | null;
  icon: string | null;
  color: ColorHex | null;
  trend: number | null;
  trendLabel: string | null;
}

/** @publish */
export interface OverviewDto {
  revenue: ReportMetricDto;
  orders: ReportMetricDto;
  customers: ReportMetricDto;
  conversionRate: ReportMetricDto;
  topKpis: KpiDto[];
  recentOrders: OrderDto[];
  lowStockAlerts: LowStockAlertDto[];
}
