// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum TrackingEventCategory {
  PageView = 'page_view',
  UserAction = 'user_action',
  Ecommerce = 'ecommerce',
  Error = 'error',
  Performance = 'performance',
  Custom = 'custom',
}

/** @publish */
export interface TrackingEventDto {
  name: string;
  category: TrackingEventCategory;
  userId: UUID | null;
  sessionId: string;
  deviceId: string;
  properties: JSONObject;
  timestamp: ISODateString;
  url: string;
  referrer: string | null;
  deviceInfo: DeviceInfo;
  locale: Locale;
}

/** @publish */
export interface PageViewEventDto {
  url: string;
  title: string;
  referrer: string | null;
  timeOnPage: number | null;
  scrollDepth: number | null;
}

/** @publish */
export interface ProductViewEventDto {
  productId: UUID;
  variantId: UUID | null;
  source: 'search' | 'category' | 'recommendation' | 'direct';
  position: number | null;
}

/** @publish */
export interface AddToCartEventDto {
  productId: UUID;
  variantId: UUID;
  quantity: number;
  price: Money;
  source: string;
}

/** @publish */
export interface CheckoutEventDto {
  cartId: UUID;
  step: number;
  option: string | null;
  couponCode: string | null;
}

/** @publish */
export interface PurchaseEventDto {
  orderId: UUID;
  total: Money;
  tax: Money;
  shipping: Money;
  coupon: string | null;
  items: Array<{ productId: UUID; variantId: UUID; quantity: number; price: Money }>;
}

/** @publish */
export interface BatchTrackDto {
  events: TrackingEventDto[];
}
