// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum FunnelStep {
  Landing = 'landing',
  ProductView = 'product_view',
  AddToCart = 'add_to_cart',
  InitiateCheckout = 'initiate_checkout',
  PaymentInfo = 'payment_info',
  Purchase = 'purchase',
}

/** @publish */
export interface FunnelStepDataDto {
  step: FunnelStep;
  label: string;
  count: number;
  dropoffCount: number;
  conversionRate: number;
  avgTimeSeconds: number | null;
}

/** @publish */
export interface FunnelReportDto {
  dateRange: DateRange;
  totalSessions: number;
  completionRate: number;
  steps: FunnelStepDataDto[];
  generatedAt: ISODateString;
}

/** @publish */
export interface CohortRowDto {
  cohortDate: ISODateString;
  cohortSize: number;
  retentionByPeriod: number[];
}

/** @publish */
export interface CohortReportDto {
  dateRange: DateRange;
  granularity: ReportGranularity;
  rows: CohortRowDto[];
  generatedAt: ISODateString;
}

/** @publish */
export interface AbTestVariantDto {
  id: UUID;
  name: string;
  trafficAllocation: number;
  conversions: number;
  impressions: number;
  conversionRate: number;
  revenue: Money | null;
}

/** @publish */
export interface AbTestDto {
  id: UUID;
  name: string;
  hypothesis: string;
  variants: AbTestVariantDto[];
  startDate: ISODateString;
  endDate: ISODateString | null;
  status: 'draft' | 'running' | 'completed' | 'stopped';
  winner: UUID | null;
}

/** @publish */
export interface CreateAbTestDto {
  name: string;
  hypothesis: string;
  variants: Array<{ name: string; trafficAllocation: number }>;
  startDate: ISODateString;
  endDate: ISODateString | null;
}
