// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum ReportType {
  Sales = 'sales',
  Products = 'products',
  Customers = 'customers',
  Traffic = 'traffic',
  Conversion = 'conversion',
  Inventory = 'inventory',
  Returns = 'returns',
  Marketing = 'marketing',
}

/** @publish */
export enum ReportGranularity {
  Hour = 'hour',
  Day = 'day',
  Week = 'week',
  Month = 'month',
  Quarter = 'quarter',
  Year = 'year',
}

/** @publish */
export interface ReportMetricDto {
  key: string;
  label: string;
  value: number;
  previousValue: number | null;
  change: number | null;
  changePercent: number | null;
  unit: string | null;
}

/** @publish */
export interface ReportDataPointDto {
  timestamp: ISODateString;
  metrics: Record<string, number>;
  dimensions: Record<string, string>;
}

/** @publish */
export interface ReportDto {
  id: UUID;
  type: ReportType;
  name: string;
  dateRange: DateRange;
  granularity: ReportGranularity;
  summary: ReportMetricDto[];
  data: ReportDataPointDto[];
  generatedAt: ISODateString;
}

/** @publish */
export interface GenerateReportDto {
  type: ReportType;
  dateRange: DateRange;
  granularity: ReportGranularity;
  filters: JSONObject;
  metrics: string[];
  groupBy: string[];
}

/** @publish */
export interface SalesReportDto {
  totalRevenue: Money;
  totalOrders: number;
  averageOrderValue: Money;
  newCustomers: number;
  returningCustomers: number;
  conversionRate: number;
  topProducts: ProductSummaryDto[];
  revenueByDay: ReportDataPointDto[];
}

/** @publish */
export interface CustomerReportDto {
  totalCustomers: number;
  newCustomers: number;
  churnRate: number;
  lifetimeValue: Money;
  retentionRate: number;
  segmentation: Record<string, number>;
}
