// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum AddressType {
  Billing = 'billing',
  Shipping = 'shipping',
  Both = 'both',
}

/** @publish */
export interface AddressDto {
  id: UUID;
  type: AddressType;
  label: string | null;
  address: Address;
  isDefault: boolean;
  validated: boolean;
  verifiedAt: ISODateString | null;
}

/** @publish */
export interface CreateAddressDto {
  type: AddressType;
  label: string | null;
  address: Address;
  setAsDefault: boolean;
}

/** @publish */
export interface UpdateAddressDto {
  type: AddressType | null;
  label: string | null;
  address: Address | null;
  setAsDefault: boolean | null;
}

/** @publish */
export interface AddressListResponseDto {
  addresses: AddressDto[];
  total: number;
}

/** @publish */
export interface ValidateAddressDto {
  address: Address;
  strict: boolean;
}

/** @publish */
export interface ValidateAddressResponseDto {
  valid: boolean;
  normalized: Address | null;
  suggestions: Address[];
  issues: string[];
}
