// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum ApiKeyStatus {
  Active = 'active',
  Revoked = 'revoked',
  Expired = 'expired',
}

/** @publish */
export enum ApiKeyScope {
  ReadOnly = 'read_only',
  ReadWrite = 'read_write',
  Admin = 'admin',
  Webhook = 'webhook',
  Custom = 'custom',
}

/** @publish */
export interface ApiKeyDto {
  id: UUID;
  name: string;
  prefix: string;
  scope: ApiKeyScope;
  status: ApiKeyStatus;
  lastUsedAt: ISODateString | null;
  expiresAt: ISODateString | null;
  createdAt: ISODateString;
  allowedIps: string[];
}

/** @publish */
export interface CreateApiKeyDto {
  name: string;
  scope: ApiKeyScope;
  expiresAt: ISODateString | null;
  allowedIps: string[];
  customScopes: PermissionDto[];
}

/** @publish */
export interface CreateApiKeyResponseDto {
  apiKey: ApiKeyDto;
  secret: string;
}

/** @publish */
export interface RevokeApiKeyDto {
  reason: string | null;
}

/** @publish */
export interface ApiKeyListResponseDto {
  keys: ApiKeyDto[];
  total: number;
}
