// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export interface LoginDto {
  email: EmailAddress;
  password: string;
  rememberMe: boolean;
  mfaCode: string | null;
  captchaToken: string | null;
}

/** @publish */
export interface LoginResponseDto {
  accessToken: string;
  refreshToken: string;
  tokenType: string;
  expiresIn: number;
  user: UserSummaryDto;
  mfaRequired: boolean;
}

/** @publish */
export interface RefreshTokenDto {
  refreshToken: string;
}

/** @publish */
export interface LogoutDto {
  refreshToken: string;
  allDevices: boolean;
}

/** @publish */
export interface RegisterDto {
  email: EmailAddress;
  username: string;
  password: string;
  firstName: string;
  lastName: string;
  inviteCode: string | null;
  agreedToTerms: boolean;
  marketingConsent: boolean;
}

/** @publish */
export interface VerifyEmailDto {
  token: string;
}

/** @publish */
export interface ForgotPasswordDto {
  email: EmailAddress;
  captchaToken: string | null;
}

/** @publish */
export interface ResetPasswordDto {
  token: string;
  newPassword: string;
  confirmPassword: string;
}

/** @publish */
export interface OAuthCallbackDto {
  code: string;
  state: string;
  provider: AuthProvider;
}

/** @publish */
export interface MfaEnrollDto {
  type: 'totp' | 'sms' | 'email';
  phoneNumber: PhoneNumberString | null;
}

/** @publish */
export interface MfaVerifyDto {
  code: string;
  type: 'totp' | 'sms' | 'email';
}

/** @publish */
export interface MfaBackupCodesDto {
  codes: string[];
}

/** @publish */
export interface SsoInitDto {
  provider: AuthProvider;
  redirectUri: string;
  state: string;
}

/** @publish */
export interface TokenIntrospectDto {
  token: string;
  tokenType: string;
}

/** @publish */
export interface TokenIntrospectResponseDto {
  active: boolean;
  sub: UUID;
  scope: string;
  exp: number;
  iat: number;
  roles: UserRole[];
}
