// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum NotificationChannel {
  Email = 'email',
  SMS = 'sms',
  Push = 'push',
  InApp = 'in_app',
  Webhook = 'webhook',
}

/** @publish */
export enum NotificationEvent {
  OrderPlaced = 'order_placed',
  OrderShipped = 'order_shipped',
  OrderDelivered = 'order_delivered',
  OrderCancelled = 'order_cancelled',
  PaymentSuccess = 'payment_success',
  PaymentFailed = 'payment_failed',
  AccountLogin = 'account_login',
  PasswordChanged = 'password_changed',
  ProfileUpdated = 'profile_updated',
  PromotionAvailable = 'promotion_available',
}

/** @publish */
export interface ChannelPreferenceDto {
  channel: NotificationChannel;
  enabled: boolean;
  frequency: 'instant' | 'hourly' | 'daily' | 'weekly';
  quietHoursStart: number | null;
  quietHoursEnd: number | null;
}

/** @publish */
export interface NotificationPreferenceDto {
  event: NotificationEvent;
  channels: ChannelPreferenceDto[];
  enabled: boolean;
}

/** @publish */
export interface UserNotificationPreferencesDto {
  userId: UUID;
  preferences: NotificationPreferenceDto[];
  globalOptOut: boolean;
  updatedAt: ISODateString;
}

/** @publish */
export interface UpdateNotificationPreferencesDto {
  preferences: NotificationPreferenceDto[];
  globalOptOut: boolean | null;
}
