// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum PermissionAction {
  Create = 'create',
  Read = 'read',
  Update = 'update',
  Delete = 'delete',
  Publish = 'publish',
  Approve = 'approve',
  Manage = 'manage',
  Export = 'export',
  Import = 'import',
}

/** @publish */
export enum PermissionResource {
  Users = 'users',
  Orders = 'orders',
  Products = 'products',
  Payments = 'payments',
  Reports = 'reports',
  Settings = 'settings',
  Webhooks = 'webhooks',
  ApiKeys = 'api_keys',
}

/** @publish */
export interface PermissionDto {
  id: UUID;
  action: PermissionAction;
  resource: PermissionResource;
  scope: 'own' | 'team' | 'all';
  conditions: JSONObject;
}

/** @publish */
export interface RoleDto {
  id: UUID;
  name: string;
  description: string;
  permissions: PermissionDto[];
  isSystem: boolean;
  createdAt: ISODateString;
}

/** @publish */
export interface AssignRoleDto {
  userId: UUID;
  roleId: UUID;
  expiresAt: ISODateString | null;
}

/** @publish */
export interface CheckPermissionDto {
  userId: UUID;
  action: PermissionAction;
  resource: PermissionResource;
  resourceId: UUID | null;
}

/** @publish */
export interface CheckPermissionResponseDto {
  allowed: boolean;
  reason: string | null;
  conditions: JSONObject;
}

/** @publish */
export interface BulkCheckPermissionsDto {
  checks: CheckPermissionDto[];
}

/** @publish */
export interface BulkCheckPermissionsResponseDto {
  results: CheckPermissionResponseDto[];
}
