// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum SessionStatus {
  Active = 'active',
  Expired = 'expired',
  Revoked = 'revoked',
}

/** @publish */
export interface DeviceInfo {
  deviceId: string;
  userAgent: string;
  browser: string;
  os: string;
  platform: string;
  mobile: boolean;
  ip: string;
  country: CountryCode | null;
  city: string | null;
}

/** @publish */
export interface SessionDto {
  id: UUID;
  userId: UUID;
  status: SessionStatus;
  device: DeviceInfo;
  createdAt: ISODateString;
  lastActiveAt: ISODateString;
  expiresAt: ISODateString;
  current: boolean;
}

/** @publish */
export interface ActiveSessionsResponseDto {
  sessions: SessionDto[];
  total: number;
}

/** @publish */
export interface RevokeSessionDto {
  sessionId: UUID;
  reason: string | null;
}

/** @publish */
export interface RevokeAllSessionsDto {
  exceptCurrent: boolean;
  reason: string | null;
}
