// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export interface CreateUserDto {
  email: EmailAddress;
  username: string;
  password: string;
  firstName: string;
  lastName: string;
  role: UserRole;
  locale: Locale | null;
  timezone: Timezone | null;
  inviteToken: string | null;
}

/** @publish */
export interface UpdateUserDto {
  firstName: string | null;
  lastName: string | null;
  displayName: string | null;
  bio: string | null;
  website: string | null;
  location: string | null;
  locale: Locale | null;
  timezone: Timezone | null;
  gender: Gender | null;
  birthDate: ISODateString | null;
}

/** @publish */
export interface UpdatePasswordDto {
  currentPassword: string;
  newPassword: string;
  confirmPassword: string;
}

/** @publish */
export interface ChangeEmailDto {
  newEmail: EmailAddress;
  password: string;
}

/** @publish */
export interface UserFilterDto {
  status: UserStatus | null;
  role: UserRole | null;
  authProvider: AuthProvider | null;
  emailVerified: boolean | null;
  search: string | null;
  createdAfter: ISODateString | null;
  createdBefore: ISODateString | null;
}

/** @publish */
export interface UserListResponseDto {
  users: UserSummaryDto[];
  pageInfo: PageInfo;
  totalCount: number;
}

/** @publish */
export interface BulkUpdateUsersDto {
  userIds: UUID[];
  status: UserStatus | null;
  role: UserRole | null;
  reason: string;
}

/** @publish */
export interface UserImportRowDto {
  email: EmailAddress;
  username: string;
  firstName: string;
  lastName: string;
  role: UserRole;
  sendInvite: boolean;
}

/** @publish */
export interface UserImportResponseDto {
  created: number;
  updated: number;
  failed: number;
  errors: ApiError[];
}

/** @publish */
export interface MergeUsersDto {
  sourceUserId: UUID;
  targetUserId: UUID;
  reason: string;
}
