// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum UserStatus {
  Active = 'active',
  Inactive = 'inactive',
  Suspended = 'suspended',
  Banned = 'banned',
  PendingVerification = 'pending_verification',
  Deleted = 'deleted',
}

/** @publish */
export enum UserRole {
  SuperAdmin = 'super_admin',
  Admin = 'admin',
  Manager = 'manager',
  Staff = 'staff',
  Customer = 'customer',
  Guest = 'guest',
  ServiceAccount = 'service_account',
}

/** @publish */
export enum AuthProvider {
  Local = 'local',
  Google = 'google',
  Facebook = 'facebook',
  Apple = 'apple',
  Microsoft = 'microsoft',
  GitHub = 'github',
  SAML = 'saml',
  OIDC = 'oidc',
}

/** @publish */
export enum Gender {
  Male = 'male',
  Female = 'female',
  NonBinary = 'non_binary',
  PreferNotToSay = 'prefer_not_to_say',
  Other = 'other',
}

/** @publish */
export interface UserIdentity {
  id: UUID;
  email: EmailAddress;
  username: string;
  roles: UserRole[];
  status: UserStatus;
  authProvider: AuthProvider;
}

/** @publish */
export interface UserProfile {
  firstName: string;
  lastName: string;
  displayName: string;
  bio: string | null;
  avatarUrl: string | null;
  website: string | null;
  location: string | null;
  gender: Gender | null;
  birthDate: ISODateString | null;
  locale: Locale;
  timezone: Timezone;
}

/** @publish */
export interface UserPreferences {
  newsletter: boolean;
  smsNotifications: boolean;
  pushNotifications: boolean;
  marketingEmails: boolean;
  theme: 'light' | 'dark' | 'system';
  language: Locale;
  dateFormat: string;
  timeFormat: '12h' | '24h';
  currency: Currency;
}

/** @publish */
export interface UserDto {
  id: UUID;
  email: EmailAddress;
  username: string;
  profile: UserProfile;
  preferences: UserPreferences;
  status: UserStatus;
  roles: UserRole[];
  authProvider: AuthProvider;
  emailVerified: boolean;
  phoneVerified: boolean;
  createdAt: ISODateString;
  updatedAt: ISODateString;
  lastLoginAt: ISODateString | null;
}

/** @publish */
export interface UserSummaryDto {
  id: UUID;
  email: EmailAddress;
  username: string;
  displayName: string;
  avatarUrl: string | null;
  status: UserStatus;
  roles: UserRole[];
}
