// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum InventoryStatus {
  InStock = 'in_stock',
  LowStock = 'low_stock',
  OutOfStock = 'out_of_stock',
  Discontinued = 'discontinued',
  OnBackorder = 'on_backorder',
  PreOrder = 'pre_order',
}

/** @publish */
export enum StockMovementType {
  Purchase = 'purchase',
  Sale = 'sale',
  Return = 'return',
  Adjustment = 'adjustment',
  Transfer = 'transfer',
  WriteOff = 'write_off',
  ReservedHold = 'reserved_hold',
  HoldReleased = 'hold_released',
}

/** @publish */
export enum WarehouseType {
  Primary = 'primary',
  Secondary = 'secondary',
  ThirdParty = 'third_party',
  DropShip = 'drop_ship',
  Virtual = 'virtual',
}

/** @publish */
export enum AdjustmentReason {
  DamagedGoods = 'damaged_goods',
  CountDiscrepancy = 'count_discrepancy',
  FoundStock = 'found_stock',
  ExpiredGoods = 'expired_goods',
  Other = 'other',
}
