// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { InventoryStatus } from './enums.js';
import { UUID, ISODateString } from '../shared/common.js';

/** @publish */
export interface InventoryLevelDto {
  productId: UUID;
  variantId: UUID | null;
  warehouseId: UUID;
  onHand: number;
  reserved: number;
  available: number;
  incoming: number;
  status: InventoryStatus;
  lowStockThreshold: number;
  updatedAt: ISODateString;
}
/** @publish */
export interface InventoryItemDto {
  id: UUID;
  sku: string;
  productName: string;
  variantName: string | null;
  levels: InventoryLevelDto[];
  totalOnHand: number;
  totalAvailable: number;
}
/** @publish */
export interface UpdateInventoryDto {
  onHand: number | null;
  lowStockThreshold: number | null;
}
/** @publish */
export interface InventoryAlertDto {
  id: UUID;
  productId: UUID;
  variantId: UUID | null;
  warehouseId: UUID;
  type: 'low_stock' | 'out_of_stock' | 'overstock';
  currentLevel: number;
  threshold: number;
  createdAt: ISODateString;
}
