// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { InventoryItemDto, InventoryAlertDto } from './inventory.dto.js';
import { StockMovementDto } from './movement.dto.js';
import { InventoryStatus } from './enums.js';
import { PageInfo } from '../shared/pagination.js';

/** @publish */
export interface InventoryListResponse {
  items: InventoryItemDto[];
  pageInfo: PageInfo;
}
/** @publish */
export interface MovementListResponse {
  items: StockMovementDto[];
  pageInfo: PageInfo;
}
/** @publish */
export interface InventoryFilterDto {
  warehouseId: string | null;
  status: InventoryStatus | null;
  search: string | null;
  lowStockOnly: boolean;
}
/** @publish */
export interface InventoryStatsDto {
  totalSkus: number;
  inStock: number;
  lowStock: number;
  outOfStock: number;
  totalValue: number;
  pendingAlerts: number;
}
/** @publish */
export interface StockForecastDto {
  productId: string;
  variantId: string | null;
  currentStock: number;
  predictedDemand30Days: number;
  reorderPoint: number;
  suggestedReorderQty: number;
}
