// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { StockMovementType, AdjustmentReason } from './enums.js';
import { UUID, ISODateString } from '../shared/common.js';

/** @publish */
export interface StockMovementDto {
  id: UUID;
  productId: UUID;
  variantId: UUID | null;
  warehouseId: UUID;
  type: StockMovementType;
  quantity: number;
  previousLevel: number;
  newLevel: number;
  reference: string | null;
  notes: string | null;
  createdBy: UUID;
  createdAt: ISODateString;
}
/** @publish */
export interface AdjustInventoryDto {
  productId: UUID;
  variantId: UUID | null;
  warehouseId: UUID;
  quantity: number;
  reason: AdjustmentReason;
  notes: string | null;
}
/** @publish */
export interface TransferStockDto {
  productId: UUID;
  variantId: UUID | null;
  fromWarehouseId: UUID;
  toWarehouseId: UUID;
  quantity: number;
  notes: string | null;
}
/** @publish */
export interface BulkAdjustmentDto {
  adjustments: AdjustInventoryDto[];
  applyAll: boolean;
}
