// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { WarehouseType } from './enums.js';
import { UUID, ISODateString, Address, GeoCoordinates } from '../shared/common.js';

/** @publish */
export interface WarehouseDto {
  id: UUID;
  name: string;
  code: string;
  type: WarehouseType;
  address: Address;
  coordinates: GeoCoordinates | null;
  isActive: boolean;
  priority: number;
  createdAt: ISODateString;
}
/** @publish */
export interface CreateWarehouseDto {
  name: string;
  code: string;
  type: WarehouseType;
  address: Address;
  priority: number;
}
/** @publish */
export interface UpdateWarehouseDto {
  name: string | null;
  isActive: boolean | null;
  priority: number | null;
}
/** @publish */
export interface WarehouseZoneDto {
  id: UUID;
  warehouseId: UUID;
  name: string;
  description: string | null;
  capacity: number | null;
  usedCapacity: number;
}
