import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { minimatch } from 'minimatch';
import type { ExtractionResult, ExtractedFile } from './extractor.js';

export interface EmitterOptions {
  /** Absolute path to the output directory root (e.g. /project/generated). */
  outDir: string;
  /** When true, log what would be written but don't touch the filesystem. */
  dryRun?: boolean;
  /**
   * Controls how extracted files are grouped into output .d.ts files.
   *
   * - `"per-file"` (default): one .d.ts per source file.
   * - `"single"`: all declarations merged into a single `index.d.ts`; no barrel.
   * - `Record<string, string[]>`: map output filename → glob patterns matched against
   *   each source file's absolute path. Unmatched files are emitted per-file.
   */
  outputGrouping?: 'per-file' | 'single' | Record<string, string[]>;
}

export interface EmittedFile {
  path: string;
  content: string;
}

export interface EmitResult {
  files: EmittedFile[];
  barrelPath: string;
}

const AUTO_GENERATED_HEADER = '// This file was auto-generated by typeship. Do not edit manually.';

/** Regex that matches a `import type { ... } from '...' ` line. */
const IMPORT_TYPE_RE = /^import type \{([^}]+)\} from '([^']+)';$/;

/**
 * Merges multiple ExtractedFiles into a single .d.ts string.
 *
 * In `single` mode (no `pathCtx`): all relative imports are stripped because
 * every referenced type will be in the same file.
 *
 * In Record-grouping mode (`pathCtx` provided):
 * - Imports whose source resolves to a file in the SAME group are stripped.
 * - Imports whose source resolves to a DIFFERENT output file are rewritten to
 *   the flat `./outputFileName.js` form and deduplicated at the top.
 * - All other imports (external packages, unresolvable) are kept as-is.
 */
function mergeContents(
  files: ExtractedFile[],
  pathCtx?: {
    /** Absolute source paths of all files in this group (intra-group → strip). */
    sameGroupPaths: Set<string>;
    /** Maps absolute source path → output .d.ts filename for every known file. */
    pathToOutputMap: Map<string, string>;
  },
): string {
  // Accumulate cross-group imports keyed by rewritten specifier for deduplication.
  const crossGroupImports = new Map<string, Set<string>>();

  const sections = files.map((f) => {
    const withoutHeader = f.content.replace(`${AUTO_GENERATED_HEADER}\n`, '').trimStart();
    const sourceDir = dirname(f.originalPath);

    const filteredLines = withoutHeader.split('\n').filter((line) => {
      const trimmed = line.trim();
      const m = trimmed.match(IMPORT_TYPE_RE);
      if (!m) return true; // not an import line → keep

      const specifier = m[2]!;
      if (!specifier.startsWith('.')) return true; // external package → keep

      if (!pathCtx) {
        // single mode: strip all relative imports
        return false;
      }

      // Resolve specifier to an absolute source .ts path.
      const absPath = resolve(sourceDir, specifier.replace(/\.js$/, '.ts'));

      if (pathCtx.sameGroupPaths.has(absPath)) {
        // Intra-group: type will be present in the same merged file → strip.
        return false;
      }

      const outputFile = pathCtx.pathToOutputMap.get(absPath);
      if (outputFile) {
        // Cross-group: collect for deduped import block at the top.
        const flatSpecifier = `./${outputFile.replace(/\.d\.ts$/, '.js')}`;
        if (!crossGroupImports.has(flatSpecifier)) {
          crossGroupImports.set(flatSpecifier, new Set());
        }
        const names = m[1]!.trim();
        for (const name of names.split(',').map((s) => s.trim())) {
          crossGroupImports.get(flatSpecifier)!.add(name);
        }
        return false; // will be emitted as a deduplicated block
      }

      // Unknown relative import (external or unresolvable) → keep as-is.
      return true;
    });

    return filteredLines.join('\n').trimStart();
  });

  const body = sections.join('\n').trimEnd();

  if (crossGroupImports.size > 0) {
    const importBlock = [...crossGroupImports.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([spec, names]) => `import type { ${[...names].sort().join(', ')} } from '${spec}';`)
      .join('\n');
    return `${AUTO_GENERATED_HEADER}\n\n${importBlock}\n\n${body}\n`;
  }

  return `${AUTO_GENERATED_HEADER}\n\n${body}\n`;
}

/**
 * Groups extracted files by the Record<string, string[]> strategy.
 * Returns { grouped, ungrouped } where grouped maps output filename → merged content,
 * and ungrouped contains files that matched no pattern (emitted per-file).
 */
function applyRecordGrouping(
  files: ExtractedFile[],
  grouping: Record<string, string[]>,
): { grouped: Map<string, ExtractedFile[]>; ungrouped: ExtractedFile[] } {
  const grouped = new Map<string, ExtractedFile[]>(
    Object.keys(grouping).map((k) => [k, []]),
  );
  const ungrouped: ExtractedFile[] = [];

  for (const file of files) {
    let matched = false;
    for (const [outputName, patterns] of Object.entries(grouping)) {
      if (patterns.some((p) => minimatch(file.originalPath, p))) {
        grouped.get(outputName)!.push(file);
        matched = true;
        break;
      }
    }
    if (!matched) {
      ungrouped.push(file);
    }
  }

  return { grouped, ungrouped };
}

/**
 * Writes extracted .d.ts declaration files and a barrel index.d.ts into outDir/src/.
 * Returns the list of files that were (or would be) written.
 */
export function emit(
  extraction: ExtractionResult,
  options: EmitterOptions,
): EmitResult {
  const srcDir = resolve(options.outDir, 'src');
  const dryRun = options.dryRun ?? false;
  const grouping = options.outputGrouping ?? 'per-file';

  if (!dryRun) {
    mkdirSync(srcDir, { recursive: true });
  }

  const emitted: EmittedFile[] = [];
  let barrelEntries: string[] = [];

  if (grouping === 'single') {
    // All declarations merged into a single index.d.ts; no separate barrel needed.
    const mergedContent = mergeContents(extraction.files);
    const dest = join(srcDir, 'index.d.ts');
    emitted.push({ path: dest, content: mergedContent });
    if (!dryRun) {
      writeFileSync(dest, mergedContent, 'utf8');
    }
    // In single mode, index.d.ts IS the barrel — point barrelPath at it directly.
    const barrelPath = dest;
    if (!dryRun) {
      for (const f of emitted) {
        if (!existsSync(f.path)) {
          throw new Error(`Emitter failed: expected file not found at ${f.path}`);
        }
      }
    }
    return { files: emitted, barrelPath };
  }

  if (grouping !== 'per-file' && typeof grouping === 'object') {
    // Record-based grouping
    const { grouped, ungrouped } = applyRecordGrouping(extraction.files, grouping);

    // Build absolute source path → output filename map for import rewriting.
    const pathToOutputMap = new Map<string, string>();
    for (const [outputName, groupFiles] of grouped.entries()) {
      for (const f of groupFiles) pathToOutputMap.set(f.originalPath, outputName);
    }
    for (const f of ungrouped) pathToOutputMap.set(f.originalPath, f.fileName);

    for (const [outputName, groupFiles] of grouped.entries()) {
      if (groupFiles.length === 0) continue;
      const sameGroupPaths = new Set(groupFiles.map((f) => f.originalPath));
      const content = mergeContents(groupFiles, { sameGroupPaths, pathToOutputMap });
      const dest = join(srcDir, outputName);
      emitted.push({ path: dest, content });
      if (!dryRun) {
        writeFileSync(dest, content, 'utf8');
      }
      barrelEntries.push(outputName);
    }

    for (const file of ungrouped) {
      const dest = join(srcDir, file.fileName);
      emitted.push({ path: dest, content: file.content });
      if (!dryRun) {
        writeFileSync(dest, file.content, 'utf8');
      }
      barrelEntries.push(file.fileName);
    }
  } else {
    // Default per-file mode
    for (const file of extraction.files) {
      const dest = join(srcDir, file.fileName);
      emitted.push({ path: dest, content: file.content });
      if (!dryRun) {
        writeFileSync(dest, file.content, 'utf8');
      }
      barrelEntries.push(file.fileName);
    }
  }

  // Generate barrel file re-exporting from all output files
  const barrelLines = [
    AUTO_GENERATED_HEADER,
    '',
    ...barrelEntries.map(
      (name) => `export * from './${name.replace(/\.d\.ts$/, '.js')}';`,
    ),
    '',
  ];
  const barrelContent = barrelLines.join('\n');
  const barrelPath = join(srcDir, 'index.d.ts');

  emitted.push({ path: barrelPath, content: barrelContent });
  if (!dryRun) {
    writeFileSync(barrelPath, barrelContent, 'utf8');
  }

  // Verify written files exist (skip in dry-run)
  if (!dryRun) {
    for (const f of emitted) {
      if (!existsSync(f.path)) {
        throw new Error(`Emitter failed: expected file not found at ${f.path}`);
      }
    }
  }

  return { files: emitted, barrelPath };
}

export interface EmitterOptions {
  /** Absolute path to the output directory root (e.g. /project/generated). */
  outDir: string;
  /** When true, log what would be written but don't touch the filesystem. */
  dryRun?: boolean;
  /**
   * Controls how extracted files are grouped into output .d.ts files.
   *
   * - `"per-file"` (default): one .d.ts per source file.
   * - `"single"`: all declarations merged into a single `index.d.ts`; no barrel.
   * - `Record<string, string[]>`: map output filename → glob patterns matched against
   *   each source file's absolute path. Unmatched files are emitted per-file.
   */
  outputGrouping?: 'per-file' | 'single' | Record<string, string[]>;
}

export interface EmittedFile {
  path: string;
  content: string;
}

export interface EmitResult {
  files: EmittedFile[];
  barrelPath: string;
}


