// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum ContentStatus {
  Draft = 'draft',
  Published = 'published',
  Archived = 'archived',
  Scheduled = 'scheduled',
}

/** @publish */
export enum ContentType {
  BlogPost = 'blog_post',
  Page = 'page',
  FAQ = 'faq',
  LandingPage = 'landing_page',
  EmailTemplate = 'email_template',
  PushTemplate = 'push_template',
}

/** @publish */
export interface ContentBlockDto {
  id: UUID;
  type: string;
  data: JSONObject;
  sortOrder: number;
}

/** @publish */
export interface ContentDto {
  id: UUID;
  type: ContentType;
  status: ContentStatus;
  title: MultiLocaleField;
  slug: Slug;
  body: ContentBlockDto[];
  excerpt: string | null;
  featuredImageId: UUID | null;
  authorId: UUID;
  tags: Tag[];
  seo: ProductSeoDto;
  publishedAt: ISODateString | null;
  scheduledAt: ISODateString | null;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

/** @publish */
export interface CreateContentDto {
  type: ContentType;
  title: MultiLocaleField;
  slug: Slug;
  body: ContentBlockDto[];
  excerpt: string | null;
  status: ContentStatus;
  publishedAt: ISODateString | null;
}

/** @publish */
export interface UpdateContentDto {
  title: MultiLocaleField | null;
  body: ContentBlockDto[] | null;
  excerpt: string | null;
  status: ContentStatus | null;
  publishedAt: ISODateString | null;
}

/** @publish */
export interface ContentListResponseDto {
  items: ContentDto[];
  pageInfo: PageInfo;
}

/** @publish */
export interface PublishContentDto {
  publishedAt: ISODateString | null;
  notify: boolean;
}
