// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum RecommendationStrategy {
  Collaborative = 'collaborative',
  ContentBased = 'content_based',
  Trending = 'trending',
  CrossSell = 'cross_sell',
  UpSell = 'up_sell',
  FrequentlyBoughtTogether = 'frequently_bought_together',
  RecentlyViewed = 'recently_viewed',
  Personalized = 'personalized',
}

/** @publish */
export interface RecommendationRequestDto {
  strategy: RecommendationStrategy;
  productId: UUID | null;
  userId: UUID | null;
  sessionId: string;
  limit: number;
  excludeIds: UUID[];
  context: JSONObject;
}

/** @publish */
export interface RecommendationDto {
  productId: UUID;
  score: number;
  reason: string | null;
  strategy: RecommendationStrategy;
}

/** @publish */
export interface RecommendationResponseDto {
  recommendations: ProductSummaryDto[];
  strategy: RecommendationStrategy;
  responseTime: number;
}

/** @publish */
export interface RecommendationFeedbackDto {
  recommendationId: UUID;
  productId: UUID;
  action: 'click' | 'add_to_cart' | 'purchase' | 'dismiss';
  sessionId: string;
}
