// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum SearchResultType {
  Product = 'product',
  Category = 'category',
  Collection = 'collection',
  Blog = 'blog',
  Page = 'page',
}

/** @publish */
export enum SearchSortOption {
  Relevance = 'relevance',
  PriceAsc = 'price_asc',
  PriceDesc = 'price_desc',
  Newest = 'newest',
  BestSelling = 'best_selling',
  Rating = 'rating',
  Alphabetical = 'alphabetical',
}

/** @publish */
export interface SearchFacetValueDto {
  value: string;
  label: string;
  count: number;
  selected: boolean;
}

/** @publish */
export interface SearchFacetDto {
  key: string;
  label: string;
  type: 'checkbox' | 'range' | 'color' | 'rating';
  values: SearchFacetValueDto[];
  minValue: number | null;
  maxValue: number | null;
}

/** @publish */
export interface SearchResultDto {
  id: UUID;
  type: SearchResultType;
  title: string;
  description: string | null;
  url: string;
  imageUrl: string | null;
  price: Money | null;
  rating: number | null;
  reviewCount: number;
  inStock: boolean;
  tags: Tag[];
  highlight: Record<string, string[]>;
  score: number;
}

/** @publish */
export interface SearchResponseDto {
  results: SearchResultDto[];
  facets: SearchFacetDto[];
  pageInfo: PageInfo;
  totalCount: number;
  queryTime: number;
  spellSuggestion: string | null;
  redirectUrl: string | null;
}

/** @publish */
export interface SearchQueryDto {
  query: string;
  types: SearchResultType[] | null;
  facets: Record<string, string[]>;
  priceRange: DateRange | null;
  sort: SearchSortOption;
  page: number;
  pageSize: number;
  includeOutOfStock: boolean;
}

/** @publish */
export interface AutocompleteDto {
  query: string;
  limit: number;
  types: SearchResultType[] | null;
}

/** @publish */
export interface AutocompleteResponseDto {
  suggestions: string[];
  products: ProductSummaryDto[];
  categories: CategoryDto[];
}
