// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum StorefrontSection {
  Hero = 'hero',
  FeaturedProducts = 'featured_products',
  Categories = 'categories',
  BannerAd = 'banner_ad',
  RecentlyViewed = 'recently_viewed',
  Recommendations = 'recommendations',
  Testimonials = 'testimonials',
  Newsletter = 'newsletter',
}

/** @publish */
export interface StorefrontBannerDto {
  id: UUID;
  imageId: UUID;
  altText: string;
  linkUrl: string | null;
  title: string | null;
  subtitle: string | null;
  ctaLabel: string | null;
  ctaUrl: string | null;
  startAt: ISODateString | null;
  endAt: ISODateString | null;
  active: boolean;
}

/** @publish */
export interface StorefrontSectionDto {
  id: UUID;
  type: StorefrontSection;
  title: string | null;
  subtitle: string | null;
  sortOrder: number;
  config: JSONObject;
  active: boolean;
}

/** @publish */
export interface StorefrontLayoutDto {
  id: UUID;
  name: string;
  sections: StorefrontSectionDto[];
  isDefault: boolean;
  updatedAt: ISODateString;
}

/** @publish */
export interface UpdateStorefrontLayoutDto {
  sections: StorefrontSectionDto[];
}

/** @publish */
export interface ThemeDto {
  id: UUID;
  name: string;
  version: string;
  colors: Record<string, ColorHex>;
  fonts: Record<string, string>;
  settings: JSONObject;
  active: boolean;
}

/** @publish */
export interface UpdateThemeSettingsDto {
  colors: Record<string, ColorHex> | null;
  fonts: Record<string, string> | null;
  settings: JSONObject | null;
}
