// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum WishlistVisibility {
  Private = 'private',
  Public = 'public',
  Shared = 'shared',
}

/** @publish */
export interface WishlistItemDto {
  id: UUID;
  productId: UUID;
  variantId: UUID | null;
  product: ProductSummaryDto;
  note: string | null;
  priority: number;
  addedAt: ISODateString;
}

/** @publish */
export interface WishlistDto {
  id: UUID;
  userId: UUID;
  name: string;
  visibility: WishlistVisibility;
  shareToken: string | null;
  items: WishlistItemDto[];
  itemCount: number;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

/** @publish */
export interface CreateWishlistDto {
  name: string;
  visibility: WishlistVisibility;
}

/** @publish */
export interface UpdateWishlistDto {
  name: string | null;
  visibility: WishlistVisibility | null;
}

/** @publish */
export interface AddToWishlistDto {
  productId: UUID;
  variantId: UUID | null;
  note: string | null;
  priority: number;
}

/** @publish */
export interface MoveWishlistItemDto {
  targetWishlistId: UUID;
}

/** @publish */
export interface WishlistListResponseDto {
  wishlists: WishlistDto[];
  total: number;
}

/** @publish */
export interface ShareWishlistDto {
  emails: EmailAddress[];
  message: string | null;
}
