// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum AttributeType {
  Text = 'text',
  Number = 'number',
  Boolean = 'boolean',
  Date = 'date',
  Select = 'select',
  MultiSelect = 'multi_select',
  Color = 'color',
  File = 'file',
}

/** @publish */
export interface AttributeValueDto {
  raw: unknown;
  formatted: string;
  unit: string | null;
}

/** @publish */
export interface AttributeDto {
  id: UUID;
  name: string;
  handle: string;
  type: AttributeType;
  description: string | null;
  required: boolean;
  filterable: boolean;
  comparable: boolean;
  visible: boolean;
  sortOrder: number;
  options: string[] | null;
  unit: string | null;
  defaultValue: AttributeValueDto | null;
}

/** @publish */
export interface ProductAttributeValueDto {
  attributeId: UUID;
  attributeName: string;
  value: AttributeValueDto;
  variantSpecific: boolean;
}

/** @publish */
export interface SetAttributeValueDto {
  attributeId: UUID;
  value: unknown;
}

/** @publish */
export interface AttributeSetDto {
  id: UUID;
  name: string;
  attributes: AttributeDto[];
  productCount: number;
}

/** @publish */
export interface CreateAttributeDto {
  name: string;
  handle: string;
  type: AttributeType;
  required: boolean;
  filterable: boolean;
  options: string[] | null;
  unit: string | null;
}
