// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum CategoryDisplayType {
  Grid = 'grid',
  List = 'list',
  Featured = 'featured',
}

/** @publish */
export interface CategoryDto {
  id: UUID;
  name: string;
  slug: Slug;
  description: string | null;
  parentId: UUID | null;
  path: string;
  depth: number;
  imageId: UUID | null;
  displayType: CategoryDisplayType;
  sortOrder: number;
  productCount: number;
  childCount: number;
  isActive: boolean;
  seo: ProductSeoDto;
  createdAt: ISODateString;
}

/** @publish */
export interface CategoryTreeNodeDto {
  id: UUID;
  name: string;
  slug: Slug;
  children: CategoryTreeNodeDto[];
  productCount: number;
  depth: number;
}

/** @publish */
export interface CreateCategoryDto {
  name: string;
  slug: Slug;
  description: string | null;
  parentId: UUID | null;
  displayType: CategoryDisplayType;
  sortOrder: number;
  isActive: boolean;
}

/** @publish */
export interface UpdateCategoryDto {
  name: string | null;
  slug: Slug | null;
  description: string | null;
  parentId: UUID | null;
  displayType: CategoryDisplayType | null;
  sortOrder: number | null;
  isActive: boolean | null;
}

/** @publish */
export interface ReorderCategoriesDto {
  categoryIds: UUID[];
}

/** @publish */
export interface MoveCategoryDto {
  categoryId: UUID;
  newParentId: UUID | null;
}
