// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum CollectionType {
  Manual = 'manual',
  Automatic = 'automatic',
  Mixed = 'mixed',
}

/** @publish */
export interface CollectionRuleDto {
  field: string;
  operator: 'equals' | 'contains' | 'starts_with' | 'ends_with' | 'greater_than' | 'less_than';
  value: string;
}

/** @publish */
export interface CollectionDto {
  id: UUID;
  name: string;
  slug: Slug;
  description: string | null;
  type: CollectionType;
  rules: CollectionRuleDto[];
  sortOrder: string;
  productCount: number;
  imageId: UUID | null;
  isActive: boolean;
  publishedAt: ISODateString | null;
  seo: ProductSeoDto;
  createdAt: ISODateString;
}

/** @publish */
export interface CreateCollectionDto {
  name: string;
  slug: Slug;
  description: string | null;
  type: CollectionType;
  rules: CollectionRuleDto[];
  sortOrder: string;
  isActive: boolean;
}

/** @publish */
export interface UpdateCollectionDto {
  name: string | null;
  slug: Slug | null;
  description: string | null;
  rules: CollectionRuleDto[] | null;
  sortOrder: string | null;
  isActive: boolean | null;
}

/** @publish */
export interface AddProductsToCollectionDto {
  productIds: UUID[];
}

/** @publish */
export interface CollectionListResponseDto {
  collections: CollectionDto[];
  pageInfo: PageInfo;
}
