// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum InventoryAdjustmentReason {
  Sale = 'sale',
  Return = 'return',
  Restock = 'restock',
  Damage = 'damage',
  Transfer = 'transfer',
  Correction = 'correction',
  Write_off = 'write_off',
  Reserved = 'reserved',
}

/** @publish */
export enum InventoryStatus {
  InStock = 'in_stock',
  LowStock = 'low_stock',
  OutOfStock = 'out_of_stock',
  Discontinued = 'discontinued',
  Backordered = 'backordered',
}

/** @publish */
export interface InventoryLocationDto {
  id: UUID;
  name: string;
  address: Address;
  isDefault: boolean;
  active: boolean;
}

/** @publish */
export interface InventoryLevelDto {
  variantId: UUID;
  locationId: UUID;
  available: number;
  onHand: number;
  reserved: number;
  incoming: number;
  status: InventoryStatus;
  lowStockThreshold: number | null;
  updatedAt: ISODateString;
}

/** @publish */
export interface InventoryAdjustmentDto {
  id: UUID;
  variantId: UUID;
  locationId: UUID;
  quantity: number;
  reason: InventoryAdjustmentReason;
  note: string | null;
  actorId: UUID;
  createdAt: ISODateString;
}

/** @publish */
export interface AdjustInventoryDto {
  variantId: UUID;
  locationId: UUID;
  quantity: number;
  reason: InventoryAdjustmentReason;
  note: string | null;
}

/** @publish */
export interface TransferInventoryDto {
  variantId: UUID;
  fromLocationId: UUID;
  toLocationId: UUID;
  quantity: number;
  note: string | null;
}

/** @publish */
export interface InventorySnapshotDto {
  locationId: UUID;
  levels: InventoryLevelDto[];
  createdAt: ISODateString;
}

/** @publish */
export interface LowStockAlertDto {
  variantId: UUID;
  locationId: UUID;
  current: number;
  threshold: number;
  productId: UUID;
  productName: string;
  sku: string;
}
