// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum PriceListType {
  Sale = 'sale',
  B2B = 'b2b',
  VIP = 'vip',
  Employee = 'employee',
  Wholesale = 'wholesale',
}

/** @publish */
export enum PriceRuleType {
  Percentage = 'percentage',
  Fixed = 'fixed',
  Override = 'override',
}

/** @publish */
export interface PriceListDto {
  id: UUID;
  name: string;
  type: PriceListType;
  currency: Currency;
  startsAt: ISODateString | null;
  endsAt: ISODateString | null;
  customerGroups: string[];
  isActive: boolean;
  priority: number;
  createdAt: ISODateString;
}

/** @publish */
export interface PriceRuleDto {
  id: UUID;
  priceListId: UUID;
  type: PriceRuleType;
  value: number;
  minQuantity: number;
  maxQuantity: number | null;
  variantId: UUID | null;
  productId: UUID | null;
  categoryId: UUID | null;
}

/** @publish */
export interface CreatePriceListDto {
  name: string;
  type: PriceListType;
  currency: Currency;
  startsAt: ISODateString | null;
  endsAt: ISODateString | null;
  customerGroups: string[];
}

/** @publish */
export interface AddPriceRuleDto {
  type: PriceRuleType;
  value: number;
  minQuantity: number;
  maxQuantity: number | null;
  variantId: UUID | null;
  productId: UUID | null;
  categoryId: UUID | null;
}

/** @publish */
export interface ComputedPriceDto {
  variantId: UUID;
  basePrice: Money;
  finalPrice: Money;
  discountAmount: Money;
  appliedPriceListId: UUID | null;
  appliedRuleId: UUID | null;
}

/** @publish */
export interface BulkComputePricesDto {
  variantIds: UUID[];
  customerId: UUID | null;
  currency: Currency;
  quantity: number;
}
