// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum ProductStatus {
  Draft = 'draft',
  Active = 'active',
  Inactive = 'inactive',
  Discontinued = 'discontinued',
  ComingSoon = 'coming_soon',
  OutOfStock = 'out_of_stock',
}

/** @publish */
export enum ProductType {
  Physical = 'physical',
  Digital = 'digital',
  Service = 'service',
  Bundle = 'bundle',
  Subscription = 'subscription',
  GiftCard = 'gift_card',
}

/** @publish */
export enum StockPolicy {
  Allow = 'allow',
  Deny = 'deny',
  Continue = 'continue',
}

/** @publish */
export enum WeightUnit {
  Gram = 'g',
  Kilogram = 'kg',
  Ounce = 'oz',
  Pound = 'lb',
}

/** @publish */
export enum DimensionUnit {
  Millimeter = 'mm',
  Centimeter = 'cm',
  Inch = 'in',
  Foot = 'ft',
}

/** @publish */
export interface ProductDimensions {
  length: number;
  width: number;
  height: number;
  unit: DimensionUnit;
}

/** @publish */
export interface ProductWeight {
  value: number;
  unit: WeightUnit;
}

/** @publish */
export interface ProductSeoDto {
  title: string;
  description: string;
  keywords: string[];
  slug: Slug;
  canonicalUrl: string | null;
  ogImageId: UUID | null;
}

/** @publish */
export interface ProductDto {
  id: UUID;
  name: string;
  description: string;
  type: ProductType;
  status: ProductStatus;
  sku: string;
  barcode: string | null;
  price: Money;
  compareAtPrice: Money | null;
  costPrice: Money | null;
  weight: ProductWeight | null;
  dimensions: ProductDimensions | null;
  images: ImageDto[];
  tags: Tag[];
  taxCode: string | null;
  requiresShipping: boolean;
  isGiftCard: boolean;
  trackInventory: boolean;
  stockPolicy: StockPolicy;
  seo: ProductSeoDto;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

/** @publish */
export interface ProductSummaryDto {
  id: UUID;
  name: string;
  sku: string;
  status: ProductStatus;
  type: ProductType;
  price: Money;
  primaryImageUrl: string | null;
  stockCount: number;
  slug: Slug;
}
