// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum ReviewStatus {
  Pending = 'pending',
  Approved = 'approved',
  Rejected = 'rejected',
  Flagged = 'flagged',
}

/** @publish */
export interface ReviewDto {
  id: UUID;
  productId: UUID;
  userId: UUID;
  author: UserSummaryDto;
  rating: number;
  title: string;
  body: string;
  status: ReviewStatus;
  verifiedPurchase: boolean;
  helpfulCount: number;
  notHelpfulCount: number;
  images: ImageDto[];
  response: string | null;
  respondedAt: ISODateString | null;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}

/** @publish */
export interface CreateReviewDto {
  productId: UUID;
  rating: number;
  title: string;
  body: string;
  imageIds: UUID[];
}

/** @publish */
export interface UpdateReviewDto {
  rating: number | null;
  title: string | null;
  body: string | null;
  imageIds: UUID[] | null;
}

/** @publish */
export interface RespondToReviewDto {
  response: string;
}

/** @publish */
export interface ModerateReviewDto {
  status: ReviewStatus;
  reason: string | null;
}

/** @publish */
export interface ReviewSummaryDto {
  productId: UUID;
  averageRating: number;
  totalCount: number;
  distribution: Record<string, number>;
  verifiedCount: number;
}

/** @publish */
export interface ReviewListResponseDto {
  reviews: ReviewDto[];
  summary: ReviewSummaryDto;
  pageInfo: PageInfo;
}
