// This file is part of the extra-large-project performance fixture.
// Generated by gen-extra-large-project.mjs — do not edit manually.

/** @publish */
export enum VariantStatus {
  Active = 'active',
  Inactive = 'inactive',
  Archived = 'archived',
}

/** @publish */
export interface ProductOptionDto {
  id: UUID;
  name: string;
  values: string[];
  sortOrder: number;
}

/** @publish */
export interface VariantOptionValueDto {
  optionId: UUID;
  optionName: string;
  value: string;
}

/** @publish */
export interface VariantDto {
  id: UUID;
  productId: UUID;
  sku: string;
  barcode: string | null;
  status: VariantStatus;
  optionValues: VariantOptionValueDto[];
  price: Money;
  compareAtPrice: Money | null;
  costPrice: Money | null;
  weight: ProductWeight | null;
  images: ImageDto[];
  stockCount: number;
  stockPolicy: StockPolicy;
  position: number;
  createdAt: ISODateString;
}

/** @publish */
export interface CreateVariantDto {
  sku: string;
  barcode: string | null;
  optionValues: VariantOptionValueDto[];
  price: Money;
  compareAtPrice: Money | null;
  costPrice: Money | null;
  weight: ProductWeight | null;
  stockCount: number;
}

/** @publish */
export interface UpdateVariantDto {
  sku: string | null;
  price: Money | null;
  compareAtPrice: Money | null;
  costPrice: Money | null;
  weight: ProductWeight | null;
  status: VariantStatus | null;
}

/** @publish */
export interface VariantListResponseDto {
  variants: VariantDto[];
  total: number;
}

/** @publish */
export interface BulkUpdateVariantPricesDto {
  updates: Array<{ variantId: UUID; price: Money; compareAtPrice?: Money | null }>;
}
