// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ReviewType } from './enums.js';

/** @publish */
export interface CreateReviewDto {
  productId: string;
  orderId: string | null;
  type: ReviewType;
  rating: number;
  title: string;
  body: string;
  pros: string[];
  cons: string[];
  imageIds: string[];
}
/** @publish */
export interface UpdateReviewDto {
  rating: number | null;
  title: string | null;
  body: string | null;
  pros: string[] | null;
  cons: string[] | null;
}
/** @publish */
export interface ModerateReviewDto {
  status: string;
  moderatorNote: string | null;
}
/** @publish */
export interface ReportReviewDto {
  reviewId: string;
  reason: string;
  details: string | null;
}
/** @publish */
export interface VoteReviewDto {
  reviewId: string;
  vote: 'helpful' | 'not_helpful';
}
/** @publish */
export interface ReviewResponseDto {
  id: string;
  reviewId: string;
  body: string;
  isSellerResponse: boolean;
  createdAt: string;
}
/** @publish */
export interface CreateReviewResponseDto {
  body: string;
}
