// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

/** @publish */
export enum ReviewStatus {
  Pending = 'pending',
  Approved = 'approved',
  Rejected = 'rejected',
  Flagged = 'flagged',
  Removed = 'removed',
}

/** @publish */
export enum ReviewType {
  Product = 'product',
  Seller = 'seller',
  Delivery = 'delivery',
}

/** @publish */
export enum ReportReason {
  Spam = 'spam',
  Inappropriate = 'inappropriate',
  FakeReview = 'fake_review',
  OffTopic = 'off_topic',
  Other = 'other',
}
