// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ReviewDto, ReviewSummaryDto, RatingSummaryDto } from './review.dto.js';
import { ReviewStatus, ReviewType } from './enums.js';
import { PageInfo, SortField } from '../shared/pagination.js';
import { DateRange } from '../shared/common.js';

/** @publish */
export interface ReviewListResponse {
  items: ReviewSummaryDto[];
  pageInfo: PageInfo;
  sort: SortField | null;
  summary: RatingSummaryDto;
}
/** @publish */
export interface ReviewDetailResponse {
  review: ReviewDto;
  rating: RatingSummaryDto;
}
/** @publish */
export interface ReviewFilterDto {
  productId: string | null;
  userId: string | null;
  type: ReviewType | null;
  status: ReviewStatus | null;
  minRating: number | null;
  maxRating: number | null;
  verifiedOnly: boolean;
  dateRange: DateRange | null;
}
/** @publish */
export interface ReviewStatsDto {
  total: number;
  approved: number;
  pending: number;
  average: number;
  distribution: Record<string,number>;
}
