// This file is part of the large-project performance fixture.
// Generated by gen-large-project.mjs — do not edit manually.

import { ReviewStatus, ReviewType } from './enums.js';
import { UUID, ISODateString } from '../shared/common.js';
import { ImageDto } from '../shared/media.js';

/** @publish */
export interface RatingBreakdownDto {
  stars: number;
  count: number;
  percentage: number;
}
/** @publish */
export interface RatingSummaryDto {
  average: number;
  count: number;
  breakdown: RatingBreakdownDto[];
}
/** @publish */
export interface ReviewVoteDto {
  helpful: number;
  notHelpful: number;
  userVote: 'helpful' | 'not_helpful' | null;
}
/** @publish */
export interface ReviewDto {
  id: UUID;
  productId: UUID;
  userId: UUID;
  orderId: UUID | null;
  type: ReviewType;
  status: ReviewStatus;
  rating: number;
  title: string;
  body: string;
  pros: string[];
  cons: string[];
  images: ImageDto[];
  votes: ReviewVoteDto;
  verifiedPurchase: boolean;
  createdAt: ISODateString;
  updatedAt: ISODateString;
}
/** @publish */
export interface ReviewSummaryDto {
  id: UUID;
  rating: number;
  title: string;
  verifiedPurchase: boolean;
  createdAt: ISODateString;
}
